"""Pure permission data: catalogue, role compat mapping, endpoint mapping.

No auth/db/fastapi import, so the security-critical mapping is unit-testable in
isolation (like app.scope). Generated from the real endpoint matrix; mirrored in
the base by migrations 0075/0076. The resolver and the FastAPI dependency live in
app.permissions_rbac.
"""
# ruff: noqa: E501
from __future__ import annotations

CATALOGUE: dict[str, dict[str, str]] = {
    'acces.administrer': {'domaine': 'acces', 'libelle': 'Acces et groupes - administrer', 'risque': 'critique', 'portee': 'global'},
    'acces.systeme': {'domaine': 'acces', 'libelle': 'Acces et groupes - administration systeme', 'risque': 'critique', 'portee': 'global'},
    'anniversaires.gerer': {'domaine': 'anniversaires', 'libelle': 'Anniversaires - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'attestations.gerer': {'domaine': 'attestations', 'libelle': 'Attestations - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'audit.administrer': {'domaine': 'audit', 'libelle': "Journal d'audit - administrer", 'risque': 'eleve', 'portee': 'global'},
    'bergers.consulter': {'domaine': 'bergers', 'libelle': 'Bergers - consulter', 'risque': 'faible', 'portee': 'scope'},
    # Collaboration access is a global app-entry permission: the fine boundary is
    # per-space membership (collab_espace_membre, require_espace_role), not an
    # organisational perimeter. It is declared 'global' rather than 'scope' because
    # collaboration never consumes require_perimetre, so a perimeter-scoped grant of
    # these keys would be inert (permissions_effectives only counts global grants).
    'canal.administrer': {'domaine': 'canal', 'libelle': 'Canal - administrer', 'risque': 'critique', 'portee': 'global'},
    'canal.traiter': {'domaine': 'canal', 'libelle': 'Canal - traiter les instructions', 'risque': 'eleve', 'portee': 'global'},
    'canal.voir': {'domaine': 'canal', 'libelle': 'Canal - voir les instructions', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.gerer': {'domaine': 'collaboration', 'libelle': 'Collaboration - gerer', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.superviser': {'domaine': 'collaboration', 'libelle': 'Collaboration - superviser', 'risque': 'faible', 'portee': 'global'},
    'commissions.administrer': {'domaine': 'commissions', 'libelle': 'Commissions et missions - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'commissions.consulter': {'domaine': 'commissions', 'libelle': 'Commissions et missions - consulter', 'risque': 'faible', 'portee': 'scope'},
    'comptage.controler': {'domaine': 'comptage', 'libelle': 'Comptage - controler', 'risque': 'moyen', 'portee': 'scope'},
    'comptage.superviser': {'domaine': 'comptage', 'libelle': 'Comptage - superviser', 'risque': 'faible', 'portee': 'scope'},
    'comptes.administrer': {'domaine': 'comptes', 'libelle': 'Comptes - administrer', 'risque': 'critique', 'portee': 'global'},
    'comptes.systeme': {'domaine': 'comptes', 'libelle': 'Comptes - administration systeme', 'risque': 'critique', 'portee': 'global'},
    'consentements.administrer': {'domaine': 'consentements', 'libelle': 'Consentements - administrer', 'risque': 'eleve', 'portee': 'global'},
    'consentements.consulter': {'domaine': 'consentements', 'libelle': 'Consentements - consulter', 'risque': 'faible', 'portee': 'scope'},
    'controle.controler': {'domaine': 'controle', 'libelle': 'Controle - controler', 'risque': 'moyen', 'portee': 'scope'},
    'deblocage.superviser': {'domaine': 'deblocage', 'libelle': 'Deblocage - superviser', 'risque': 'faible', 'portee': 'scope'},
    'demandes.gerer': {'domaine': 'demandes', 'libelle': 'Demandes - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'demandes.superviser': {'domaine': 'demandes', 'libelle': 'Demandes - superviser', 'risque': 'faible', 'portee': 'scope'},
    'documents.gerer': {'domaine': 'documents', 'libelle': 'Documents - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'doublons.administrer': {'domaine': 'doublons', 'libelle': 'Doublons - administrer', 'risque': 'critique', 'portee': 'global'},
    'doublons.consulter': {'domaine': 'doublons', 'libelle': 'Doublons - consulter', 'risque': 'critique', 'portee': 'global'},
    'doublons.gerer': {'domaine': 'doublons', 'libelle': 'Doublons - gerer', 'risque': 'critique', 'portee': 'global'},
    'evenements.consulter': {'domaine': 'evenements', 'libelle': 'Evenements - consulter', 'risque': 'faible', 'portee': 'scope'},
    'evenements.gerer': {'domaine': 'evenements', 'libelle': 'Evenements - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'evenements.superviser': {'domaine': 'evenements', 'libelle': 'Evenements - superviser', 'risque': 'faible', 'portee': 'scope'},
    'fonctions.consulter': {'domaine': 'fonctions', 'libelle': 'Fonctions et titres - consulter', 'risque': 'faible', 'portee': 'scope'},
    'fonctions.gerer': {'domaine': 'fonctions', 'libelle': 'Fonctions et titres - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'inscriptions.administrer': {'domaine': 'inscriptions', 'libelle': 'Inscriptions - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'inscriptions.gerer': {'domaine': 'inscriptions', 'libelle': 'Inscriptions - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'integrations.administrer': {'domaine': 'integrations', 'libelle': 'Integrations - administrer', 'risque': 'eleve', 'portee': 'global'},
    'integrations.superviser': {'domaine': 'integrations', 'libelle': 'Integrations - superviser', 'risque': 'faible', 'portee': 'scope'},
    'matrice-pays.consulter': {'domaine': 'matrice-pays', 'libelle': 'Matrice pays - consulter', 'risque': 'faible', 'portee': 'scope'},
    'matrice-pays.gerer': {'domaine': 'matrice-pays', 'libelle': 'Matrice pays - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'membres.administrer': {'domaine': 'membres', 'libelle': 'Membres - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'membres.consulter': {'domaine': 'membres', 'libelle': 'Membres - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'membres.gerer': {'domaine': 'membres', 'libelle': 'Membres - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'membres.self': {'domaine': 'membres', 'libelle': 'Membres - acces personnel', 'risque': 'faible', 'portee': 'self'},
    'modeles.consulter': {'domaine': 'modeles', 'libelle': 'Modeles - consulter', 'risque': 'faible', 'portee': 'scope'},
    'modeles.gerer': {'domaine': 'modeles', 'libelle': 'Modeles - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'niveaux-engagement.consulter': {'domaine': 'niveaux-engagement', 'libelle': 'Niveaux-Engagement - consulter', 'risque': 'faible', 'portee': 'scope'},
    'niveaux-engagement.gerer': {'domaine': 'niveaux-engagement', 'libelle': 'Niveaux-Engagement - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'notifications.consulter': {'domaine': 'notifications', 'libelle': 'Notifications - consulter', 'risque': 'faible', 'portee': 'scope'},
    'notifications.gerer': {'domaine': 'notifications', 'libelle': 'Notifications - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'organisation.administrer': {'domaine': 'organisation', 'libelle': 'Organisation - administrer', 'risque': 'eleve', 'portee': 'global'},
    'organisation.consulter': {'domaine': 'organisation', 'libelle': 'Organisation - consulter', 'risque': 'faible', 'portee': 'scope'},
    'parametres.consulter': {'domaine': 'parametres', 'libelle': 'Parametres - consulter', 'risque': 'faible', 'portee': 'scope'},
    'parametres.gerer': {'domaine': 'parametres', 'libelle': 'Parametres - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'participation.consulter': {'domaine': 'participation', 'libelle': 'Participation - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'participation.gerer': {'domaine': 'participation', 'libelle': 'Participation - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'statistiques.consulter': {'domaine': 'statistiques', 'libelle': 'Statistiques - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'tags.administrer': {'domaine': 'tags', 'libelle': 'Etiquettes - administrer', 'risque': 'eleve', 'portee': 'global'},
    'terminaux.administrer': {'domaine': 'terminaux', 'libelle': 'Terminaux - administrer', 'risque': 'eleve', 'portee': 'global'},
    'terminaux.consulter': {'domaine': 'terminaux', 'libelle': 'Terminaux - consulter', 'risque': 'faible', 'portee': 'scope'},
    'tribus.administrer': {'domaine': 'tribus', 'libelle': 'Tribus - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'tribus.consulter': {'domaine': 'tribus', 'libelle': 'Tribus - consulter', 'risque': 'faible', 'portee': 'scope'},
}

# Human explanation of each atomic permission, grounded strictly in the endpoints
# it gates (ENDPOINT_PERMISSION): what it concretely allows (description) and its
# boundary, i.e. what it does NOT allow (limite). Shown in the permission matrix
# and the group editor so an administrator understands what a grant means before
# giving it. Kept separate from CATALOGUE so the security-critical catalogue shape
# (mirrored by migrations/tests) is untouched.
PERMISSION_DETAILS: dict[str, dict[str, str]] = {
    'acces.administrer': {'description': "Gerer les acces des membres: consulter le catalogue d'acces et de permissions, les groupes, les perimetres disponibles, l'acces effectif d'un membre, et ajouter ou retirer un membre d'un groupe.", 'limite': "Ne permet pas de creer, modifier ou supprimer les groupes eux-memes, ce qui releve de acces.systeme."},
    'acces.systeme': {'description': "Creer, modifier et supprimer les groupes d'acces qui structurent les droits de la plateforme.", 'limite': "Ne couvre pas l'affectation des membres aux groupes, qui releve de acces.administrer."},
    'anniversaires.gerer': {'description': "Declencher manuellement l'envoi des messages d'anniversaire aux membres.", 'limite': "Ne permet pas d'editer le modele de message d'anniversaire, qui releve de modeles.gerer, et reste borne au perimetre attribue."},
    'attestations.gerer': {'description': "Consulter la liste des attestations et valider une attestation.", 'limite': "Aucune action au-dela de la validation n'est exposee, et l'acces reste borne au perimetre attribue."},
    'audit.administrer': {'description': "Consulter le journal d'audit retracant les actions sensibles de la plateforme.", 'limite': "Lecture seule: aucune modification ni suppression des entrees d'audit n'est possible."},
    'bergers.consulter': {'description': "Consulter la liste des bergers.", 'limite': "Lecture seule bornee au perimetre: aucune creation ni modification."},
    'canal.administrer': {'description': "Administrer le canal: configurer les emetteurs autorises du bot d'instruction et les canaux additionnels.", 'limite': "Le tri et le traitement des instructions relevent de canal.traiter, la simple lecture de canal.voir."},
    'canal.traiter': {'description': "Traiter les instructions du canal: prendre en charge, affecter a un espace et a des personnes, charger vers un tableau, restituer et cloturer; creer/editer les sujets, notes et transcriptions.", 'limite': "La configuration du canal releve de canal.administrer."},
    'canal.voir': {'description': "Voir les instructions du canal (sujets, notes vocales, transcriptions, suivi) en lecture seule.", 'limite': "Ne permet ni de prendre en charge, ni d'affecter, ni d'editer, ce qui releve de canal.traiter."},
    'collaboration.gerer': {'description': "Creer et modifier le contenu collaboratif: espaces, tableaux, colonnes, cartes, checklists, pieces jointes, commentaires, etiquettes, activites et messages du canal.", 'limite': "L'action reste bornee a l'appartenance de chaque espace collaboratif (membre de l'espace), et non a un perimetre organisationnel."},
    'collaboration.superviser': {'description': "Acceder en lecture a l'application de collaboration (espaces, tableaux, cartes, calendrier, notifications, activites, recherche) et rejoindre un espace via un jeton, marquer une carte lue ou signaler sa presence.", 'limite': "Ne permet pas de creer ni de modifier espaces, tableaux ou cartes, ce qui releve de collaboration.gerer."},
    'commissions.administrer': {'description': "Creer des commissions et des missions.", 'limite': "Aucun endpoint de suppression n'est expose; la simple consultation releve de commissions.consulter et l'action reste bornee au perimetre."},
    'commissions.consulter': {'description': "Consulter la liste des commissions et des missions.", 'limite': "Lecture seule: aucune creation ni modification."},
    'comptage.controler': {'description': "Enregistrer un comptage lors d'un evenement.", 'limite': "Ne donne pas acces a la consultation consolidee du comptage (comptage.superviser) et reste borne au perimetre."},
    'comptage.superviser': {'description': "Consulter le comptage consolide d'un evenement.", 'limite': "Lecture seule: ne permet pas de saisir un comptage, ce qui releve de comptage.controler."},
    'comptes.administrer': {'description': "Consulter la liste des comptes utilisateurs (comptes d'acces a la plateforme).", 'limite': "Ne permet pas de creer ni de modifier un compte, ce qui releve de comptes.systeme."},
    'comptes.systeme': {'description': "Creer des comptes utilisateurs, individuellement ou en lot, et modifier un compte existant.", 'limite': "Aucun endpoint de suppression de compte n'est expose; la consultation de la liste releve de comptes.administrer."},
    'consentements.administrer': {'description': "Creer ou mettre a jour le texte et la version d'un consentement.", 'limite': "La consultation releve de consentements.consulter et aucune suppression n'est exposee."},
    'consentements.consulter': {'description': "Consulter les consentements et le detail de chaque version.", 'limite': "Lecture seule bornee au perimetre: aucune modification."},
    'controle.controler': {'description': "Operer le controle de presence sur le terrain: lister les evenements et membres a controler, verifier un code, enregistrer les arrivees et departs, et effectuer un pointage manuel.", 'limite': "Borne aux evenements du perimetre de controle: ne donne acces ni a la gestion des membres ni aux statistiques."},
    'deblocage.superviser': {'description': "Consulter les elements de deblocage.", 'limite': "Lecture seule bornee au perimetre: aucune action de deblocage n'est exposee."},
    'demandes.gerer': {'description': "Traiter les demandes: les prendre en charge, echanger des messages, reclamer une piece, decider des modifications et mettre a jour leur statut.", 'limite': "La consultation de la liste et du detail des demandes releve de demandes.superviser, et le traitement reste borne au perimetre."},
    'demandes.superviser': {'description': "Consulter la liste et le detail des demandes, leurs modifications et la photo en attente.", 'limite': "Lecture seule: aucune action de traitement, qui releve de demandes.gerer."},
    'documents.gerer': {'description': "Acceder au contenu et a l'URL des documents rattaches aux membres.", 'limite': "Aucun endpoint de suppression de document n'est expose, et l'acces reste borne au perimetre."},
    'doublons.administrer': {'description': "Lancer un scan de doublons et regler le seuil de detection.", 'limite': "Le tri d'une detection (confirmer, demander des documents, personnes distinctes) releve de doublons.gerer et la consultation de la liste de doublons.consulter."},
    'doublons.consulter': {'description': "Consulter la liste des doublons detectes et le seuil de detection courant.", 'limite': "Lecture seule: ne lance aucun scan et ne modifie pas le seuil."},
    'doublons.gerer': {'description': "Comparer en detail deux fiches candidates a un doublon et statuer sur une detection (confirmer le doublon, demander des documents, ou marquer comme personnes distinctes).", 'limite': "Ne lance pas de scan et ne modifie pas le seuil, ce qui releve de doublons.administrer."},
    'evenements.consulter': {'description': "Consulter les evenements, leurs pieces, leur questionnaire, les reponses et les statistiques de participation.", 'limite': "Lecture seule: aucune creation ni modification."},
    'evenements.gerer': {'description': "Creer, modifier, annuler, reactiver et supprimer des evenements, gerer leur session, leurs tags, pieces, questionnaire et occurrences, et tester la diffusion.", 'limite': "Le declenchement d'un sondage releve de evenements.superviser, et la gestion reste bornee au perimetre."},
    'evenements.superviser': {'description': "Declencher un sondage rattache a un evenement.", 'limite': "Ne donne aucun acces a la creation, a la modification ou a la consultation des evenements eux-memes."},
    'fonctions.consulter': {'description': "Consulter le referentiel des fonctions et des titres.", 'limite': "Lecture seule: aucune modification."},
    'fonctions.gerer': {'description': "Creer, modifier et supprimer des fonctions et des titres du referentiel.", 'limite': "Ne couvre pas l'attribution d'une fonction a un membre, qui releve de membres.gerer."},
    'inscriptions.administrer': {'description': "Inscrire des membres a l'unite ou en lot, convertir des engagements en membres et relancer un mot de passe.", 'limite': "Le suivi courant et la decision sur une inscription relevent de inscriptions.gerer, et l'action reste bornee au perimetre."},
    'inscriptions.gerer': {'description': "Suivre les inscriptions et engagements (tableau de bord, invitations, import, dossiers, corrections, compteurs) et statuer sur une inscription.", 'limite': "La creation directe de membres et la conversion des engagements relevent de inscriptions.administrer."},
    'integrations.administrer': {'description': "Configurer les integrations: fournisseurs d'IA (creation, activation, test, suppression), parametres d'integration et test d'envoi d'e-mail.", 'limite': "La simple lecture de l'etat des integrations releve de integrations.superviser."},
    'integrations.superviser': {'description': "Consulter l'etat et le statut des integrations.", 'limite': "Lecture seule: ne configure ni ne teste aucune integration."},
    'matrice-pays.consulter': {'description': "Consulter la matrice des pays et leurs regles de signature.", 'limite': "Lecture seule: aucune modification."},
    'matrice-pays.gerer': {'description': "Modifier la configuration de signature d'un pays dans la matrice.", 'limite': "Ne cree ni ne supprime d'entree pays, et reste borne au perimetre attribue."},
    'membres.administrer': {'description': "Creer, modifier et supprimer un membre, le bloquer ou le debloquer, et consulter ses connexions et sa gouvernance.", 'limite': "L'attribution des groupes d'acces releve de acces.administrer, et l'action reste bornee au perimetre."},
    'membres.consulter': {'description': "Consulter les fonctions et la photo d'un membre.", 'limite': "Lecture partielle: la liste et la fiche complete des membres relevent de membres.gerer."},
    'membres.gerer': {'description': "Consulter la liste et la fiche des membres, gerer leurs fonctions (attribuer, modifier, retirer), demander un document et consulter l'annuaire des pays.", 'limite': "La creation, la suppression et le blocage des membres relevent de membres.administrer, et la gestion reste bornee au perimetre."},
    'membres.self': {'description': "Acces du membre a son propre espace personnel: regler sa langue, son theme, sa double authentification et son canal MFA, consulter son etat MFA et revoquer un appareil de confiance.", 'limite': "Strictement limite a son propre compte: aucun acces aux donnees d'autres membres."},
    'modeles.consulter': {'description': "Consulter le modele de message d'anniversaire.", 'limite': "Lecture seule: aucune modification."},
    'modeles.gerer': {'description': "Modifier le modele de message d'anniversaire.", 'limite': "Se limite au modele d'anniversaire et ne declenche pas les envois, qui relevent de anniversaires.gerer."},
    'niveaux-engagement.consulter': {'description': "Consulter la liste des niveaux d'engagement.", 'limite': "Lecture seule: aucune modification."},
    'niveaux-engagement.gerer': {'description': "Creer, modifier et supprimer les niveaux d'engagement.", 'limite': "Action bornee au perimetre attribue."},
    'notifications.consulter': {'description': "Consulter les types de notifications et le journal des echecs d'envoi.", 'limite': "Lecture seule: ne declenche ni ne configure aucun envoi."},
    'notifications.gerer': {'description': "Configurer les types de notifications, declencher les envois (sondages, envoi quotidien) et marquer un echec comme resolu.", 'limite': "Action bornee au perimetre attribue."},
    'organisation.administrer': {'description': "Creer, modifier, publier et supprimer les entites d'organisation: coordinations, intendances et sous-commissions.", 'limite': "La simple consultation de ces entites releve de organisation.consulter."},
    'organisation.consulter': {'description': "Consulter les coordinations, intendances et sous-commissions.", 'limite': "Lecture seule: aucune modification."},
    'parametres.consulter': {'description': "Consulter les parametres de fonctionnement (fenetre de questionnaire, sondage de pointage).", 'limite': "Lecture seule: aucune modification."},
    'parametres.gerer': {'description': "Modifier les parametres de fonctionnement (fenetre de questionnaire, sondage de pointage).", 'limite': "Se limite a ces parametres et reste borne au perimetre attribue."},
    'participation.consulter': {'description': "Consulter la participation globale consolidee.", 'limite': "Lecture seule: aucune modification."},
    'participation.gerer': {'description': "Acceder a l'analyse detaillee de la participation d'un membre.", 'limite': "Aucune action de modification des enregistrements de presence n'est exposee, et l'acces reste borne au perimetre."},
    'statistiques.consulter': {'description': "Consulter les statistiques consolidees de la plateforme.", 'limite': "Lecture seule: aucune modification."},
    'tags.administrer': {'description': "Gerer les etiquettes: creer une etiquette, consulter les etiquettes de demandes et decider de leur application a une demande.", 'limite': "Aucun endpoint de suppression d'etiquette n'est expose."},
    'terminaux.administrer': {'description': "Enregistrer un terminal et modifier sa configuration.", 'limite': "La simple consultation releve de terminaux.consulter, et aucune suppression n'est exposee."},
    'terminaux.consulter': {'description': "Consulter la liste des terminaux.", 'limite': "Lecture seule: aucune modification."},
    'tribus.administrer': {'description': "Creer une tribu et administrer les tribus (nom, description, publication, reaffectation, suppression, designation du patriarche).", 'limite': "La consultation des tribus releve de tribus.consulter; l'edition structurelle passe par organisation.administrer."},
    'tribus.consulter': {'description': "Consulter la liste des tribus.", 'limite': "Lecture seule: aucune modification."},
}

ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    'membre': frozenset(['membres.self']),
    'controleur': frozenset(['bergers.consulter', 'commissions.consulter', 'comptage.controler', 'consentements.consulter', 'controle.controler', 'doublons.consulter', 'evenements.consulter', 'fonctions.consulter', 'matrice-pays.consulter', 'membres.consulter', 'membres.self', 'modeles.consulter', 'niveaux-engagement.consulter', 'notifications.consulter', 'organisation.consulter', 'parametres.consulter', 'participation.consulter', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'gestionnaire': frozenset(['anniversaires.gerer', 'attestations.gerer', 'bergers.consulter', 'canal.traiter', 'canal.voir', 'collaboration.gerer', 'collaboration.superviser', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.gerer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'direction': frozenset(['bergers.consulter', 'canal.voir', 'collaboration.superviser', 'commissions.consulter', 'comptage.superviser', 'consentements.consulter', 'deblocage.superviser', 'demandes.superviser', 'doublons.consulter', 'evenements.consulter', 'evenements.superviser', 'fonctions.consulter', 'integrations.superviser', 'matrice-pays.consulter', 'membres.consulter', 'membres.self', 'modeles.consulter', 'niveaux-engagement.consulter', 'notifications.consulter', 'organisation.consulter', 'parametres.consulter', 'participation.consulter', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'admin': frozenset(['acces.administrer', 'anniversaires.gerer', 'attestations.gerer', 'audit.administrer', 'bergers.consulter', 'canal.administrer', 'canal.traiter', 'canal.voir', 'collaboration.gerer', 'collaboration.superviser', 'commissions.administrer', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'comptes.administrer', 'consentements.administrer', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.administrer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.administrer', 'inscriptions.gerer', 'integrations.administrer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.administrer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.administrer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'tags.administrer', 'terminaux.administrer', 'terminaux.consulter', 'tribus.administrer', 'tribus.consulter']),
    'super_admin': frozenset(['acces.administrer', 'acces.systeme', 'anniversaires.gerer', 'attestations.gerer', 'audit.administrer', 'bergers.consulter', 'canal.administrer', 'canal.traiter', 'canal.voir', 'collaboration.gerer', 'collaboration.superviser', 'commissions.administrer', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'comptes.administrer', 'comptes.systeme', 'consentements.administrer', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.administrer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.administrer', 'inscriptions.gerer', 'integrations.administrer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.administrer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.administrer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'tags.administrer', 'terminaux.administrer', 'terminaux.consulter', 'tribus.administrer', 'tribus.consulter']),
}

ENDPOINT_PERMISSION: dict[str, str] = {
    'GET /api/v1/admin/ai/catalogue': 'integrations.administrer',
    'GET /api/v1/admin/ai/providers': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers': 'integrations.administrer',
    'PATCH /api/v1/admin/ai/providers/{provider_id}': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers/{provider_id}/activer': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers/{provider_id}/desactiver': 'integrations.administrer',
    'DELETE /api/v1/admin/ai/providers/{provider_id}': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers/{provider_id}/test': 'integrations.administrer',
    'GET /api/v1/collaboration/canal': 'canal.voir',
    'GET /api/v1/collaboration/canal/compteur': 'canal.voir',
    'GET /api/v1/collaboration/modeles-catalogue': 'collaboration.superviser',
    'POST /api/v1/collaboration/canal': 'canal.traiter',
    'PATCH /api/v1/collaboration/canal/{message_id}': 'canal.traiter',
    'DELETE /api/v1/collaboration/canal/{message_id}': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/pieces': 'canal.traiter',
    'DELETE /api/v1/collaboration/canal/pieces/{piece_id}': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/notes': 'canal.traiter',
    'POST /api/v1/collaboration/canal/notes/{note_id}/transcrire': 'canal.traiter',
    'POST /api/v1/collaboration/canal/notes/{note_id}/rediger': 'canal.traiter',
    'PATCH /api/v1/collaboration/canal/notes/{note_id}': 'canal.traiter',
    'DELETE /api/v1/collaboration/canal/notes/{note_id}': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/reponses': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/creer-carte': 'canal.traiter',
    'POST /api/v1/collaboration/canal/telegram/importer': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/prise-en-charge': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/affecter': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/charger-tableau': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/restituer': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/cloturer': 'canal.traiter',
    'DELETE /api/v1/collaboration/espaces/{espace_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/restaurer': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/restaurer': 'collaboration.gerer',
    'GET /api/v1/collaboration/corbeille': 'collaboration.superviser',
    'GET /api/v1/collaboration/reglages': 'parametres.consulter',
    'PUT /api/v1/collaboration/reglages': 'parametres.gerer',
    'GET /api/v1/collaboration/espaces/{espace_id}/emetteurs': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces/{espace_id}/canal/demander-config': 'collaboration.gerer',
    'GET /api/v1/admin/collaboration/bot-demandes': 'integrations.administrer',
    'GET /api/v1/admin/collaboration/bots': 'integrations.administrer',
    'PUT /api/v1/admin/collaboration/espaces/{espace_id}/bot': 'acces.systeme',
    'DELETE /api/v1/admin/collaboration/espaces/{espace_id}/bot': 'acces.systeme',
    'POST /api/v1/collaboration/espaces/{espace_id}/emetteurs': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/emetteurs/{utilisateur_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/canal/{message_id}/workflow': 'canal.voir',
    'DELETE /api/v1/admin/fonctions/{cle}': 'fonctions.gerer',
    'DELETE /api/v1/admin/fonctions/{cle}/definitif': 'fonctions.gerer',
    'DELETE /api/v1/admin/membres/{membre_id}': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/suppression-apercu': 'membres.administrer',
    'PATCH /api/v1/admin/membres/{membre_id}/statut': 'membres.administrer',
    'GET /api/v1/admin/technical-super-admins': 'acces.systeme',
    'POST /api/v1/admin/technical-super-admins/creer': 'acces.systeme',
    'POST /api/v1/admin/technical-super-admins/{utilisateur_id}': 'acces.systeme',
    'PATCH /api/v1/admin/technical-super-admins/{utilisateur_id}/niveau': 'acces.systeme',
    'PATCH /api/v1/admin/technical-super-admins/{utilisateur_id}/activation': 'acces.systeme',
    'DELETE /api/v1/admin/technical-super-admins/{utilisateur_id}': 'acces.systeme',
    'DELETE /api/v1/admin/technical-super-admins/{utilisateur_id}/definitif': 'acces.systeme',
    'DELETE /api/v1/admin/membres/{membre_id}/fonctions/{fonction_id}': 'membres.gerer',
    'DELETE /api/v1/admin/membres/{membre_id}/groupes/{appartenance_id}': 'acces.administrer',
    'DELETE /api/v1/admin/niveaux-engagement/{cle}': 'niveaux-engagement.gerer',
    'DELETE /api/v1/admin/niveaux-engagement/{cle}/definitif': 'niveaux-engagement.gerer',
    'DELETE /api/v1/admin/organisation/{entity}/{item_id}': 'organisation.administrer',
    'GET /api/v1/admin/annuaire/pays': 'membres.gerer',
    'GET /api/v1/admin/attestations': 'attestations.gerer',
    'GET /api/v1/admin/audit': 'audit.administrer',
    'GET /api/v1/admin/bergers': 'bergers.consulter',
    'GET /api/v1/admin/catalogue-acces': 'acces.administrer',
    'GET /api/v1/admin/catalogue-permissions': 'acces.administrer',
    'GET /api/v1/reference/cibles-activite': 'membres.self',
    'GET /api/v1/admin/cibles-activite': 'evenements.consulter',
    'POST /api/v1/admin/cibles-activite': 'parametres.gerer',
    'PATCH /api/v1/admin/cibles-activite/{code}': 'parametres.gerer',
    'DELETE /api/v1/admin/cibles-activite/{code}': 'parametres.gerer',
    'GET /api/v1/admin/cibles-activite/{code}/apercu': 'evenements.consulter',
    'GET /api/v1/admin/commissions': 'commissions.consulter',
    'GET /api/v1/admin/comptage/evenements-eligibles': 'comptage.superviser',
    'GET /api/v1/admin/comptage/{evenement_id}': 'comptage.superviser',
    'GET /api/v1/admin/consentements': 'consentements.consulter',
    'GET /api/v1/admin/consentements/{cle}': 'consentements.consulter',
    'GET /api/v1/admin/coordinations': 'organisation.consulter',
    'GET /api/v1/admin/deblocage/elements': 'deblocage.superviser',
    'GET /api/v1/admin/demandes': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}/modifications': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}/photo-pending': 'demandes.superviser',
    'GET /api/v1/admin/documents/{document_id}/content': 'documents.gerer',
    'GET /api/v1/admin/documents/{document_id}/url': 'documents.gerer',
    'GET /api/v1/admin/doublons': 'doublons.consulter',
    'GET /api/v1/admin/doublons/comparaison': 'doublons.gerer',
    'GET /api/v1/admin/doublons/fusion/apercu': 'doublons.gerer',
    'GET /api/v1/admin/doublons/seuil': 'doublons.consulter',
    'GET /api/v1/admin/evenements': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/participation-stats': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/questionnaire': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/reponses': 'evenements.consulter',
    'GET /api/v1/admin/fonctions': 'fonctions.consulter',
    'GET /api/v1/admin/fonctions/{cle}/dependances': 'fonctions.consulter',
    'POST /api/v1/admin/fonctions/{cle}/reaffecter': 'fonctions.gerer',
    'GET /api/v1/admin/groupes': 'acces.administrer',
    'GET /api/v1/admin/inscriptions': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/dashboard': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/invitations': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/template.xlsx': 'inscriptions.gerer',
    'POST /api/v1/admin/engagement/convertir': 'inscriptions.administrer',
    'POST /api/v1/admin/engagement/import': 'inscriptions.gerer',
    'POST /api/v1/admin/engagement/invitations': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/compteurs': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/{membre_id}/corrections': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/{membre_id}/dossier': 'inscriptions.gerer',
    'GET /api/v1/admin/integrations': 'integrations.administrer',
    'GET /api/v1/admin/integrations/statut': 'integrations.superviser',
    'GET /api/v1/admin/intendances': 'organisation.consulter',
    'GET /api/v1/admin/membres': 'membres.gerer',
    'GET /api/v1/admin/membres/compartiments': 'membres.gerer',
    'GET /api/v1/admin/membres/{membre_id}': 'membres.gerer',
    'GET /api/v1/admin/membres/{membre_id}/acces-effectif': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/connexions': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/fonctions': 'membres.consulter',
    'GET /api/v1/admin/membres/{membre_id}/gouvernance': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/groupes': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/participation-analytique': 'participation.gerer',
    'GET /api/v1/admin/membres/{membre_id}/photo-url': 'membres.consulter',
    'GET /api/v1/admin/modeles/anniversaire': 'modeles.consulter',
    'GET /api/v1/admin/niveaux-engagement': 'niveaux-engagement.consulter',
    'GET /api/v1/admin/niveaux-engagement/{cle}/dependances': 'niveaux-engagement.consulter',
    'POST /api/v1/admin/niveaux-engagement/{cle}/reaffecter': 'niveaux-engagement.gerer',
    'GET /api/v1/admin/notifications/echecs': 'notifications.consulter',
    'GET /api/v1/admin/notifications/types': 'notifications.consulter',
    'GET /api/v1/admin/parametres/questionnaire-fenetre': 'parametres.consulter',
    'GET /api/v1/admin/parametres/semaine-jour-debut': 'parametres.consulter',
    'GET /api/v1/admin/parametres/sondage-pointage': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/sondage-pointage': 'parametres.gerer',
    'POST /api/v1/admin/notifications/declencher-sondages': 'notifications.gerer',
    'GET /api/v1/admin/participation/global': 'participation.consulter',
    'GET /api/v1/admin/pays-signature': 'matrice-pays.consulter',
    'GET /api/v1/admin/perimetres-disponibles': 'acces.administrer',
    'GET /api/v1/admin/sous-commissions': 'organisation.consulter',
    'GET /api/v1/admin/statistiques': 'statistiques.consulter',
    'GET /api/v1/admin/tags/demandes': 'tags.administrer',
    'GET /api/v1/admin/terminaux': 'terminaux.consulter',
    'GET /api/v1/admin/applications': 'acces.administrer',
    'GET /api/v1/admin/applications/{code}/roles': 'acces.administrer',
    'GET /api/v1/admin/applications/{code}/membres': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/applications': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/applications/{code}/groupes': 'acces.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/applications/{code}': 'acces.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/applications/{code}/groupes/{groupe_id}': 'acces.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/applications/{code}/roles/{role_code}': 'acces.administrer',
    'GET /api/v1/admin/tribus': 'tribus.consulter',
    'POST /api/v1/admin/tribus': 'tribus.administrer',
    'GET /api/v1/admin/types-evenements': 'evenements.consulter',
    'GET /api/v1/admin/types-evenements/couleur-suggeree': 'evenements.consulter',
    'POST /api/v1/admin/types-evenements': 'evenements.gerer',
    'PATCH /api/v1/admin/types-evenements/{type_id}': 'evenements.gerer',
    'DELETE /api/v1/admin/types-evenements/{type_id}': 'evenements.gerer',
    'GET /api/v1/admin/utilisateurs': 'comptes.administrer',
    'GET /api/v1/collaboration/calendrier': 'collaboration.superviser',
    'GET /api/v1/collaboration/cartes/{carte_id}/commentaires': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces': 'collaboration.superviser',
    'GET /api/v1/collaboration/admin/espaces': 'acces.administrer',
    'GET /api/v1/collaboration/espaces/{espace_id}': 'collaboration.superviser',
    'GET /api/v1/collaboration/membres': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux/{tableau_id}': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/membres': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}/membres/{membre_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/membres/{membre_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/demandes': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces/{espace_id}/demandes/{demande_id}/accepter': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/demandes/{demande_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/etiquettes': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}/etiquettes/{etiquette_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/etiquettes/{etiquette_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/espaces/{espace_id}/tableaux': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}/tableaux-archives': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux-espace': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/depuis-modele': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/archive': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux-espace/{tableau_id}/participants': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/participants': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/tableaux-espace/{tableau_id}/participants/{utilisateur_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/colonnes': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux/{tableau_id}/colonnes': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/colonnes/{colonne_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/colonnes/{colonne_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/cartes': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/cartes-archivees': 'collaboration.superviser',
    'POST /api/v1/collaboration/cartes-espace': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/cartes-espace/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/deplacer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/deplacer-tableau': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/dupliquer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/archive': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/publier': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/cartes-espace/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/commentaires': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/lu': 'collaboration.superviser',
    'POST /api/v1/collaboration/commentaires/{commentaire_id}/reaction': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/checklists': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklists/{checklist_id}/items': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklist-items/{item_id}/basculer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/pieces': 'collaboration.gerer',
    'POST /api/v1/collaboration/commentaires/{commentaire_id}/pieces': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/pieces/{piece_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/couverture': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/commentaires/{commentaire_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/commentaires/{commentaire_id}': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/checklists/{checklist_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/checklists/{checklist_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklists/{checklist_id}/items/ordre': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/checklist-items/{item_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/checklist-items/{item_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklist-items/{item_id}/convertir': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux/{tableau_id}/colonnes/ordre': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/presence': 'collaboration.superviser',
    'DELETE /api/v1/collaboration/cartes-espace/{carte_id}/presence': 'collaboration.superviser',
    'GET /api/v1/collaboration/notifications': 'collaboration.superviser',
    'POST /api/v1/collaboration/notifications/{notif_id}/lue': 'collaboration.superviser',
    'POST /api/v1/collaboration/notifications/toutes-lues': 'collaboration.superviser',
    'GET /api/v1/collaboration/moi': 'collaboration.superviser',
    'POST /api/v1/collaboration/rejoindre/{jeton}': 'collaboration.superviser',
    'GET /api/v1/collaboration/mes-cartes': 'collaboration.superviser',
    'GET /api/v1/collaboration/cartes-echeance': 'collaboration.superviser',
    'GET /api/v1/collaboration/activites': 'collaboration.superviser',
    'GET /api/v1/collaboration/cibles': 'collaboration.gerer',
    'POST /api/v1/collaboration/activites': 'collaboration.gerer',
    'GET /api/v1/collaboration/activites/{evenement_id}': 'collaboration.superviser',
    'PUT /api/v1/collaboration/activites/{evenement_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/activites/{evenement_id}/annuler': 'collaboration.gerer',
    'GET /api/v1/collaboration/activites/{evenement_id}/pieces': 'collaboration.superviser',
    'POST /api/v1/collaboration/activites/{evenement_id}/pieces': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/activites/pieces/{piece_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/activites/{evenement_id}/occurrences': 'collaboration.gerer',
    'GET /api/v1/collaboration/stats': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}/stats': 'collaboration.superviser',
    'GET /api/v1/collaboration/recherche': 'collaboration.superviser',
    'GET /api/v1/controle/evenements': 'controle.controler',
    'GET /api/v1/controle/membres': 'controle.controler',
    'DELETE /api/v1/admin/groupes/{groupe_id}': 'acces.systeme',
    'PATCH /api/v1/admin/demandes/{demande_id}': 'demandes.gerer',
    'PATCH /api/v1/admin/groupes/{groupe_id}': 'acces.systeme',
    'PATCH /api/v1/admin/evenements/{evenement_id}/session': 'evenements.gerer',
    'PATCH /api/v1/admin/membres/{membre_id}': 'membres.administrer',
    'PATCH /api/v1/admin/membres/{membre_id}/fonctions/{fonction_id}': 'membres.gerer',
    'PATCH /api/v1/admin/organisation/{entity}/{item_id}': 'organisation.administrer',
    'PATCH /api/v1/admin/organisation/{entity}/{item_id}/publication': 'organisation.administrer',
    'GET /api/v1/admin/organisation/{entity}/{item_id}/dependances': 'organisation.administrer',
    'POST /api/v1/admin/organisation/{entity}/{item_id}/reaffecter': 'organisation.administrer',
    'PATCH /api/v1/admin/pays-signature/{code}': 'matrice-pays.gerer',
    'PATCH /api/v1/admin/terminaux/{terminal_id}': 'terminaux.administrer',
    'PATCH /api/v1/admin/utilisateurs/{utilisateur_id}': 'comptes.systeme',
    'PATCH /api/v1/collaboration/cartes/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/admin/anniversaires/declencher': 'anniversaires.gerer',
    'POST /api/v1/admin/attestations/{attestation_id}/valider': 'attestations.gerer',
    'POST /api/v1/admin/commissions': 'commissions.administrer',
    'POST /api/v1/admin/comptage': 'comptage.controler',
    'POST /api/v1/admin/consentements/{cle}': 'consentements.administrer',
    'POST /api/v1/admin/coordinations': 'organisation.administrer',
    'POST /api/v1/admin/demandes/{demande_id}/demander-piece': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/messages': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/modifications/decision': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/prendre-en-charge': 'demandes.gerer',
    'POST /api/v1/admin/doublons/scan': 'doublons.administrer',
    'POST /api/v1/admin/doublons/fusion': 'doublons.administrer',
    'POST /api/v1/admin/doublons/{detection_id}/statut': 'doublons.gerer',
    'POST /api/v1/admin/evenements': 'evenements.gerer',
    'PUT /api/v1/admin/evenements/{evenement_id}': 'evenements.gerer',
    'PUT /api/v1/admin/evenements/{evenement_id}/tags': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/annuler': 'evenements.gerer',
    'GET /api/v1/admin/evenements/{evenement_id}/pieces': 'evenements.consulter',
    'POST /api/v1/admin/evenements/{evenement_id}/pieces': 'evenements.gerer',
    'DELETE /api/v1/admin/evenements/pieces/{piece_id}': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/occurrences': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/reactiver': 'evenements.gerer',
    'DELETE /api/v1/admin/evenements/{evenement_id}': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/sondage': 'evenements.superviser',
    'POST /api/v1/admin/evenements/{evenement_id}/test-diffusion': 'evenements.gerer',
    'POST /api/v1/admin/fonctions': 'fonctions.gerer',
    'POST /api/v1/admin/groupes': 'acces.systeme',
    'POST /api/v1/admin/inscriptions/membre': 'inscriptions.administrer',
    'POST /api/v1/admin/inscriptions/membres-lot': 'inscriptions.administrer',
    'POST /api/v1/admin/inscriptions/{membre_id}/decision': 'inscriptions.gerer',
    'POST /api/v1/admin/inscriptions/{membre_id}/relancer-mdp': 'inscriptions.administrer',
    'POST /api/v1/admin/integrations/test-email': 'integrations.administrer',
    'POST /api/v1/admin/intendances': 'organisation.administrer',
    'POST /api/v1/admin/membres': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/bloquer': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/debloquer': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/demander-document': 'membres.gerer',
    'POST /api/v1/admin/membres/{membre_id}/fonctions': 'membres.gerer',
    'POST /api/v1/admin/membres/{membre_id}/groupes': 'acces.administrer',
    'POST /api/v1/admin/niveaux-engagement': 'niveaux-engagement.gerer',
    'POST /api/v1/admin/notifications/declencher-quotidien': 'notifications.gerer',
    'POST /api/v1/admin/notifications/echecs/{echec_id}/resolu': 'notifications.gerer',
    'POST /api/v1/admin/sous-commissions': 'organisation.administrer',
    'POST /api/v1/admin/tags': 'tags.administrer',
    'POST /api/v1/admin/tags/demandes/{demande_id}/decision': 'tags.administrer',
    'POST /api/v1/admin/terminaux': 'terminaux.administrer',
    'POST /api/v1/admin/utilisateurs': 'comptes.systeme',
    'POST /api/v1/admin/utilisateurs/lot': 'comptes.systeme',
    'POST /api/v1/collaboration/cartes': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes/{carte_id}/commentaires': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes/{carte_id}/publier': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux': 'collaboration.gerer',
    'POST /api/v1/controle/checkin': 'controle.controler',
    'POST /api/v1/controle/checkin-manuel': 'controle.controler',
    'POST /api/v1/controle/checkout': 'controle.controler',
    'POST /api/v1/controle/verify': 'controle.controler',
    'PUT /api/v1/admin/coordinations/{item_id}': 'organisation.administrer',
    'PUT /api/v1/admin/doublons/seuil': 'doublons.administrer',
    'PUT /api/v1/admin/evenements/{evenement_id}/questionnaire': 'evenements.gerer',
    'PUT /api/v1/admin/fonctions/{cle}': 'fonctions.gerer',
    'PUT /api/v1/admin/integrations/{cle}': 'integrations.administrer',
    'PUT /api/v1/admin/intendances/{item_id}': 'organisation.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/fonction': 'membres.gerer',
    'PUT /api/v1/admin/modeles/anniversaire': 'modeles.gerer',
    'PUT /api/v1/admin/niveaux-engagement/{cle}': 'niveaux-engagement.gerer',
    'PUT /api/v1/admin/notifications/types/{cle}': 'notifications.gerer',
    'PUT /api/v1/admin/parametres/questionnaire-fenetre': 'parametres.gerer',
    'PUT /api/v1/admin/parametres/semaine-jour-debut': 'parametres.gerer',
    'PUT /api/v1/admin/tribus/{tribu_id}/patriarche': 'tribus.administrer',
    'PUT /api/v1/membres/me/langue': 'membres.self',
    'PUT /api/v1/membres/me/theme': 'membres.self',
    'PUT /api/v1/membres/me/double-facteur': 'membres.self',
    'PUT /api/v1/membres/me/mfa-canal': 'membres.self',
    'GET /api/v1/membres/me/mfa': 'membres.self',
    'DELETE /api/v1/membres/me/appareils-confiance/{appareil_id}': 'membres.self',
}


def permissions_du_role(role: str) -> frozenset[str]:
    """The permissions a historical role holds (empty for an unknown role)."""
    return ROLE_PERMISSIONS.get(role, frozenset())
