"""Pure permission data: catalogue, role compat mapping, endpoint mapping.

No auth/db/fastapi import, so the security-critical mapping is unit-testable in
isolation (like app.scope). Generated from the real endpoint matrix; mirrored in
the base by migrations 0075/0076. The resolver and the FastAPI dependency live in
app.permissions_rbac.
"""
# ruff: noqa: E501
from __future__ import annotations

CATALOGUE: dict[str, dict[str, str]] = {
    'acces.administrer': {'domaine': 'acces', 'libelle': 'Acces et groupes - administrer', 'risque': 'critique', 'portee': 'global'},
    'acces.systeme': {'domaine': 'acces', 'libelle': 'Acces et groupes - administration systeme', 'risque': 'critique', 'portee': 'global'},
    'anniversaires.gerer': {'domaine': 'anniversaires', 'libelle': 'Anniversaires - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'attestations.gerer': {'domaine': 'attestations', 'libelle': 'Attestations - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'audit.administrer': {'domaine': 'audit', 'libelle': "Journal d'audit - administrer", 'risque': 'eleve', 'portee': 'global'},
    'bergers.consulter': {'domaine': 'bergers', 'libelle': 'Bergers - consulter', 'risque': 'faible', 'portee': 'scope'},
    # Collaboration access is a global app-entry permission: the fine boundary is
    # per-space membership (collab_espace_membre, require_espace_role), not an
    # organisational perimeter. It is declared 'global' rather than 'scope' because
    # collaboration never consumes require_perimetre, so a perimeter-scoped grant of
    # these keys would be inert (permissions_effectives only counts global grants).
    'collaboration.gerer': {'domaine': 'collaboration', 'libelle': 'Collaboration - gerer', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.superviser': {'domaine': 'collaboration', 'libelle': 'Collaboration - superviser', 'risque': 'faible', 'portee': 'global'},
    'commissions.administrer': {'domaine': 'commissions', 'libelle': 'Commissions et missions - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'commissions.consulter': {'domaine': 'commissions', 'libelle': 'Commissions et missions - consulter', 'risque': 'faible', 'portee': 'scope'},
    'comptage.controler': {'domaine': 'comptage', 'libelle': 'Comptage - controler', 'risque': 'moyen', 'portee': 'scope'},
    'comptage.superviser': {'domaine': 'comptage', 'libelle': 'Comptage - superviser', 'risque': 'faible', 'portee': 'scope'},
    'comptes.administrer': {'domaine': 'comptes', 'libelle': 'Comptes - administrer', 'risque': 'critique', 'portee': 'global'},
    'comptes.systeme': {'domaine': 'comptes', 'libelle': 'Comptes - administration systeme', 'risque': 'critique', 'portee': 'global'},
    'consentements.administrer': {'domaine': 'consentements', 'libelle': 'Consentements - administrer', 'risque': 'eleve', 'portee': 'global'},
    'consentements.consulter': {'domaine': 'consentements', 'libelle': 'Consentements - consulter', 'risque': 'faible', 'portee': 'scope'},
    'controle.controler': {'domaine': 'controle', 'libelle': 'Controle - controler', 'risque': 'moyen', 'portee': 'scope'},
    'deblocage.superviser': {'domaine': 'deblocage', 'libelle': 'Deblocage - superviser', 'risque': 'faible', 'portee': 'scope'},
    'demandes.gerer': {'domaine': 'demandes', 'libelle': 'Demandes - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'demandes.superviser': {'domaine': 'demandes', 'libelle': 'Demandes - superviser', 'risque': 'faible', 'portee': 'scope'},
    'documents.gerer': {'domaine': 'documents', 'libelle': 'Documents - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'doublons.administrer': {'domaine': 'doublons', 'libelle': 'Doublons - administrer', 'risque': 'critique', 'portee': 'global'},
    'doublons.consulter': {'domaine': 'doublons', 'libelle': 'Doublons - consulter', 'risque': 'critique', 'portee': 'global'},
    'doublons.gerer': {'domaine': 'doublons', 'libelle': 'Doublons - gerer', 'risque': 'critique', 'portee': 'global'},
    'evenements.consulter': {'domaine': 'evenements', 'libelle': 'Evenements - consulter', 'risque': 'faible', 'portee': 'scope'},
    'evenements.gerer': {'domaine': 'evenements', 'libelle': 'Evenements - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'evenements.superviser': {'domaine': 'evenements', 'libelle': 'Evenements - superviser', 'risque': 'faible', 'portee': 'scope'},
    'fonctions.consulter': {'domaine': 'fonctions', 'libelle': 'Fonctions et titres - consulter', 'risque': 'faible', 'portee': 'scope'},
    'fonctions.gerer': {'domaine': 'fonctions', 'libelle': 'Fonctions et titres - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'inscriptions.administrer': {'domaine': 'inscriptions', 'libelle': 'Inscriptions - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'inscriptions.gerer': {'domaine': 'inscriptions', 'libelle': 'Inscriptions - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'integrations.administrer': {'domaine': 'integrations', 'libelle': 'Integrations - administrer', 'risque': 'eleve', 'portee': 'global'},
    'integrations.superviser': {'domaine': 'integrations', 'libelle': 'Integrations - superviser', 'risque': 'faible', 'portee': 'scope'},
    'matrice-pays.consulter': {'domaine': 'matrice-pays', 'libelle': 'Matrice pays - consulter', 'risque': 'faible', 'portee': 'scope'},
    'matrice-pays.gerer': {'domaine': 'matrice-pays', 'libelle': 'Matrice pays - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'membres.administrer': {'domaine': 'membres', 'libelle': 'Membres - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'membres.consulter': {'domaine': 'membres', 'libelle': 'Membres - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'membres.gerer': {'domaine': 'membres', 'libelle': 'Membres - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'membres.self': {'domaine': 'membres', 'libelle': 'Membres - acces personnel', 'risque': 'faible', 'portee': 'self'},
    'modeles.consulter': {'domaine': 'modeles', 'libelle': 'Modeles - consulter', 'risque': 'faible', 'portee': 'scope'},
    'modeles.gerer': {'domaine': 'modeles', 'libelle': 'Modeles - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'niveaux-engagement.consulter': {'domaine': 'niveaux-engagement', 'libelle': 'Niveaux-Engagement - consulter', 'risque': 'faible', 'portee': 'scope'},
    'niveaux-engagement.gerer': {'domaine': 'niveaux-engagement', 'libelle': 'Niveaux-Engagement - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'notifications.consulter': {'domaine': 'notifications', 'libelle': 'Notifications - consulter', 'risque': 'faible', 'portee': 'scope'},
    'notifications.gerer': {'domaine': 'notifications', 'libelle': 'Notifications - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'organisation.administrer': {'domaine': 'organisation', 'libelle': 'Organisation - administrer', 'risque': 'eleve', 'portee': 'global'},
    'organisation.consulter': {'domaine': 'organisation', 'libelle': 'Organisation - consulter', 'risque': 'faible', 'portee': 'scope'},
    'parametres.consulter': {'domaine': 'parametres', 'libelle': 'Parametres - consulter', 'risque': 'faible', 'portee': 'scope'},
    'parametres.gerer': {'domaine': 'parametres', 'libelle': 'Parametres - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'participation.consulter': {'domaine': 'participation', 'libelle': 'Participation - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'participation.gerer': {'domaine': 'participation', 'libelle': 'Participation - gerer', 'risque': 'moyen', 'portee': 'scope'},
    'statistiques.consulter': {'domaine': 'statistiques', 'libelle': 'Statistiques - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'tags.administrer': {'domaine': 'tags', 'libelle': 'Etiquettes - administrer', 'risque': 'eleve', 'portee': 'global'},
    'terminaux.administrer': {'domaine': 'terminaux', 'libelle': 'Terminaux - administrer', 'risque': 'eleve', 'portee': 'global'},
    'terminaux.consulter': {'domaine': 'terminaux', 'libelle': 'Terminaux - consulter', 'risque': 'faible', 'portee': 'scope'},
    'tribus.administrer': {'domaine': 'tribus', 'libelle': 'Tribus - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'tribus.consulter': {'domaine': 'tribus', 'libelle': 'Tribus - consulter', 'risque': 'faible', 'portee': 'scope'},
}

ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    'membre': frozenset(['membres.self']),
    'controleur': frozenset(['bergers.consulter', 'commissions.consulter', 'comptage.controler', 'consentements.consulter', 'controle.controler', 'doublons.consulter', 'evenements.consulter', 'fonctions.consulter', 'matrice-pays.consulter', 'membres.consulter', 'membres.self', 'modeles.consulter', 'niveaux-engagement.consulter', 'notifications.consulter', 'organisation.consulter', 'parametres.consulter', 'participation.consulter', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'gestionnaire': frozenset(['anniversaires.gerer', 'attestations.gerer', 'bergers.consulter', 'collaboration.gerer', 'collaboration.superviser', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.gerer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'direction': frozenset(['bergers.consulter', 'collaboration.superviser', 'commissions.consulter', 'comptage.superviser', 'consentements.consulter', 'deblocage.superviser', 'demandes.superviser', 'doublons.consulter', 'evenements.consulter', 'evenements.superviser', 'fonctions.consulter', 'integrations.superviser', 'matrice-pays.consulter', 'membres.consulter', 'membres.self', 'modeles.consulter', 'niveaux-engagement.consulter', 'notifications.consulter', 'organisation.consulter', 'parametres.consulter', 'participation.consulter', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'admin': frozenset(['acces.administrer', 'anniversaires.gerer', 'attestations.gerer', 'audit.administrer', 'bergers.consulter', 'collaboration.gerer', 'collaboration.superviser', 'commissions.administrer', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'comptes.administrer', 'consentements.administrer', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.administrer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.administrer', 'inscriptions.gerer', 'integrations.administrer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.administrer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.administrer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'tags.administrer', 'terminaux.administrer', 'terminaux.consulter', 'tribus.administrer', 'tribus.consulter']),
    'super_admin': frozenset(['acces.administrer', 'acces.systeme', 'anniversaires.gerer', 'attestations.gerer', 'audit.administrer', 'bergers.consulter', 'collaboration.gerer', 'collaboration.superviser', 'commissions.administrer', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'comptes.administrer', 'comptes.systeme', 'consentements.administrer', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.administrer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.administrer', 'inscriptions.gerer', 'integrations.administrer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.administrer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.administrer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'tags.administrer', 'terminaux.administrer', 'terminaux.consulter', 'tribus.administrer', 'tribus.consulter']),
}

ENDPOINT_PERMISSION: dict[str, str] = {
    'DELETE /api/v1/admin/fonctions/{cle}': 'fonctions.gerer',
    'DELETE /api/v1/admin/membres/{membre_id}': 'membres.administrer',
    'DELETE /api/v1/admin/membres/{membre_id}/fonctions/{fonction_id}': 'membres.gerer',
    'DELETE /api/v1/admin/membres/{membre_id}/groupes/{appartenance_id}': 'acces.administrer',
    'DELETE /api/v1/admin/niveaux-engagement/{cle}': 'niveaux-engagement.gerer',
    'DELETE /api/v1/admin/organisation/{entity}/{item_id}': 'organisation.administrer',
    'GET /api/v1/admin/annuaire/pays': 'membres.gerer',
    'GET /api/v1/admin/attestations': 'attestations.gerer',
    'GET /api/v1/admin/audit': 'audit.administrer',
    'GET /api/v1/admin/bergers': 'bergers.consulter',
    'GET /api/v1/admin/catalogue-acces': 'acces.administrer',
    'GET /api/v1/admin/catalogue-permissions': 'acces.administrer',
    'GET /api/v1/admin/commissions': 'commissions.consulter',
    'GET /api/v1/admin/comptage/{evenement_id}': 'comptage.superviser',
    'GET /api/v1/admin/consentements': 'consentements.consulter',
    'GET /api/v1/admin/consentements/{cle}': 'consentements.consulter',
    'GET /api/v1/admin/coordinations': 'organisation.consulter',
    'GET /api/v1/admin/deblocage/elements': 'deblocage.superviser',
    'GET /api/v1/admin/demandes': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}/modifications': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}/photo-pending': 'demandes.superviser',
    'GET /api/v1/admin/documents/{document_id}/content': 'documents.gerer',
    'GET /api/v1/admin/documents/{document_id}/url': 'documents.gerer',
    'GET /api/v1/admin/doublons': 'doublons.consulter',
    'GET /api/v1/admin/doublons/comparaison': 'doublons.gerer',
    'GET /api/v1/admin/doublons/seuil': 'doublons.consulter',
    'GET /api/v1/admin/evenements': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/participation-stats': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/questionnaire': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/reponses': 'evenements.consulter',
    'GET /api/v1/admin/fonctions': 'fonctions.consulter',
    'GET /api/v1/admin/groupes': 'acces.administrer',
    'GET /api/v1/admin/inscriptions': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/dashboard': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/invitations': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/template.xlsx': 'inscriptions.gerer',
    'POST /api/v1/admin/engagement/convertir': 'inscriptions.administrer',
    'POST /api/v1/admin/engagement/import': 'inscriptions.gerer',
    'POST /api/v1/admin/engagement/invitations': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/compteurs': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/{membre_id}/corrections': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/{membre_id}/dossier': 'inscriptions.gerer',
    'GET /api/v1/admin/integrations': 'integrations.administrer',
    'GET /api/v1/admin/integrations/statut': 'integrations.superviser',
    'GET /api/v1/admin/intendances': 'organisation.consulter',
    'GET /api/v1/admin/membres': 'membres.gerer',
    'GET /api/v1/admin/membres/{membre_id}': 'membres.gerer',
    'GET /api/v1/admin/membres/{membre_id}/acces-effectif': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/connexions': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/fonctions': 'membres.consulter',
    'GET /api/v1/admin/membres/{membre_id}/gouvernance': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/groupes': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/participation-analytique': 'participation.gerer',
    'GET /api/v1/admin/membres/{membre_id}/photo-url': 'membres.consulter',
    'GET /api/v1/admin/modeles/anniversaire': 'modeles.consulter',
    'GET /api/v1/admin/niveaux-engagement': 'niveaux-engagement.consulter',
    'GET /api/v1/admin/notifications/echecs': 'notifications.consulter',
    'GET /api/v1/admin/notifications/types': 'notifications.consulter',
    'GET /api/v1/admin/parametres/questionnaire-fenetre': 'parametres.consulter',
    'GET /api/v1/admin/parametres/sondage-pointage': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/sondage-pointage': 'parametres.gerer',
    'POST /api/v1/admin/notifications/declencher-sondages': 'notifications.gerer',
    'GET /api/v1/admin/participation/global': 'participation.consulter',
    'GET /api/v1/admin/pays-signature': 'matrice-pays.consulter',
    'GET /api/v1/admin/perimetres-disponibles': 'acces.administrer',
    'GET /api/v1/admin/sous-commissions': 'organisation.consulter',
    'GET /api/v1/admin/statistiques': 'statistiques.consulter',
    'GET /api/v1/admin/tags/demandes': 'tags.administrer',
    'GET /api/v1/admin/terminaux': 'terminaux.consulter',
    'GET /api/v1/admin/tribus': 'tribus.consulter',
    'GET /api/v1/admin/utilisateurs': 'comptes.administrer',
    'GET /api/v1/collaboration/calendrier': 'collaboration.superviser',
    'GET /api/v1/collaboration/cartes/{carte_id}/commentaires': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}': 'collaboration.superviser',
    'GET /api/v1/collaboration/membres': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux/{tableau_id}': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/membres': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}/membres/{membre_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/membres/{membre_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/demandes': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces/{espace_id}/demandes/{demande_id}/accepter': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/demandes/{demande_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/etiquettes': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}/etiquettes/{etiquette_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/etiquettes/{etiquette_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/espaces/{espace_id}/tableaux': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}/tableaux-archives': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux-espace': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/depuis-modele': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/archive': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/colonnes': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux/{tableau_id}/colonnes': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/colonnes/{colonne_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/colonnes/{colonne_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/cartes': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/cartes-archivees': 'collaboration.superviser',
    'POST /api/v1/collaboration/cartes-espace': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/cartes-espace/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/deplacer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/deplacer-tableau': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/dupliquer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/archive': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/publier': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/cartes-espace/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/commentaires': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/lu': 'collaboration.superviser',
    'POST /api/v1/collaboration/commentaires/{commentaire_id}/reaction': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/checklists': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklists/{checklist_id}/items': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklist-items/{item_id}/basculer': 'collaboration.gerer',
    'GET /api/v1/collaboration/notifications': 'collaboration.superviser',
    'POST /api/v1/collaboration/notifications/{notif_id}/lue': 'collaboration.superviser',
    'POST /api/v1/collaboration/notifications/toutes-lues': 'collaboration.superviser',
    'GET /api/v1/collaboration/moi': 'collaboration.superviser',
    'POST /api/v1/collaboration/rejoindre/{jeton}': 'collaboration.superviser',
    'GET /api/v1/collaboration/mes-cartes': 'collaboration.superviser',
    'GET /api/v1/collaboration/cartes-echeance': 'collaboration.superviser',
    'GET /api/v1/collaboration/stats': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}/stats': 'collaboration.superviser',
    'GET /api/v1/collaboration/recherche': 'collaboration.superviser',
    'GET /api/v1/controle/evenements': 'controle.controler',
    'GET /api/v1/controle/membres': 'controle.controler',
    'DELETE /api/v1/admin/groupes/{groupe_id}': 'acces.systeme',
    'PATCH /api/v1/admin/demandes/{demande_id}': 'demandes.gerer',
    'PATCH /api/v1/admin/groupes/{groupe_id}': 'acces.systeme',
    'PATCH /api/v1/admin/evenements/{evenement_id}/session': 'evenements.gerer',
    'PATCH /api/v1/admin/membres/{membre_id}': 'membres.administrer',
    'PATCH /api/v1/admin/membres/{membre_id}/fonctions/{fonction_id}': 'membres.gerer',
    'PATCH /api/v1/admin/organisation/{entity}/{item_id}': 'organisation.administrer',
    'PATCH /api/v1/admin/organisation/{entity}/{item_id}/publication': 'organisation.administrer',
    'PATCH /api/v1/admin/pays-signature/{code}': 'matrice-pays.gerer',
    'PATCH /api/v1/admin/terminaux/{terminal_id}': 'terminaux.administrer',
    'PATCH /api/v1/admin/utilisateurs/{utilisateur_id}': 'comptes.systeme',
    'PATCH /api/v1/collaboration/cartes/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/admin/anniversaires/declencher': 'anniversaires.gerer',
    'POST /api/v1/admin/attestations/{attestation_id}/valider': 'attestations.gerer',
    'POST /api/v1/admin/commissions': 'commissions.administrer',
    'POST /api/v1/admin/comptage': 'comptage.controler',
    'POST /api/v1/admin/consentements/{cle}': 'consentements.administrer',
    'POST /api/v1/admin/coordinations': 'organisation.administrer',
    'POST /api/v1/admin/demandes/{demande_id}/demander-piece': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/messages': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/modifications/decision': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/prendre-en-charge': 'demandes.gerer',
    'POST /api/v1/admin/doublons/scan': 'doublons.administrer',
    'POST /api/v1/admin/doublons/{detection_id}/statut': 'doublons.administrer',
    'POST /api/v1/admin/evenements': 'evenements.gerer',
    'PUT /api/v1/admin/evenements/{evenement_id}': 'evenements.gerer',
    'PUT /api/v1/admin/evenements/{evenement_id}/tags': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/annuler': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/occurrences': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/reactiver': 'evenements.gerer',
    'DELETE /api/v1/admin/evenements/{evenement_id}': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/sondage': 'evenements.superviser',
    'POST /api/v1/admin/evenements/{evenement_id}/test-diffusion': 'evenements.gerer',
    'POST /api/v1/admin/fonctions': 'fonctions.gerer',
    'POST /api/v1/admin/groupes': 'acces.systeme',
    'POST /api/v1/admin/inscriptions/membre': 'inscriptions.administrer',
    'POST /api/v1/admin/inscriptions/membres-lot': 'inscriptions.administrer',
    'POST /api/v1/admin/inscriptions/{membre_id}/decision': 'inscriptions.gerer',
    'POST /api/v1/admin/inscriptions/{membre_id}/relancer-mdp': 'inscriptions.administrer',
    'POST /api/v1/admin/integrations/test-email': 'integrations.administrer',
    'POST /api/v1/admin/intendances': 'organisation.administrer',
    'POST /api/v1/admin/membres': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/bloquer': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/debloquer': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/demander-document': 'membres.gerer',
    'POST /api/v1/admin/membres/{membre_id}/fonctions': 'membres.gerer',
    'POST /api/v1/admin/membres/{membre_id}/groupes': 'acces.administrer',
    'POST /api/v1/admin/niveaux-engagement': 'niveaux-engagement.gerer',
    'POST /api/v1/admin/notifications/declencher-quotidien': 'notifications.gerer',
    'POST /api/v1/admin/notifications/echecs/{echec_id}/resolu': 'notifications.gerer',
    'POST /api/v1/admin/sous-commissions': 'organisation.administrer',
    'POST /api/v1/admin/tags': 'tags.administrer',
    'POST /api/v1/admin/tags/demandes/{demande_id}/decision': 'tags.administrer',
    'POST /api/v1/admin/terminaux': 'terminaux.administrer',
    'POST /api/v1/admin/utilisateurs': 'comptes.systeme',
    'POST /api/v1/admin/utilisateurs/lot': 'comptes.systeme',
    'POST /api/v1/collaboration/cartes': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes/{carte_id}/commentaires': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes/{carte_id}/publier': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux': 'collaboration.gerer',
    'POST /api/v1/controle/checkin': 'controle.controler',
    'POST /api/v1/controle/checkin-manuel': 'controle.controler',
    'POST /api/v1/controle/checkout': 'controle.controler',
    'POST /api/v1/controle/verify': 'controle.controler',
    'PUT /api/v1/admin/coordinations/{item_id}': 'organisation.administrer',
    'PUT /api/v1/admin/doublons/seuil': 'doublons.administrer',
    'PUT /api/v1/admin/evenements/{evenement_id}/questionnaire': 'evenements.gerer',
    'PUT /api/v1/admin/fonctions/{cle}': 'fonctions.gerer',
    'PUT /api/v1/admin/integrations/{cle}': 'integrations.administrer',
    'PUT /api/v1/admin/intendances/{item_id}': 'organisation.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/fonction': 'membres.gerer',
    'PUT /api/v1/admin/modeles/anniversaire': 'modeles.gerer',
    'PUT /api/v1/admin/niveaux-engagement/{cle}': 'niveaux-engagement.gerer',
    'PUT /api/v1/admin/notifications/types/{cle}': 'notifications.gerer',
    'PUT /api/v1/admin/parametres/questionnaire-fenetre': 'parametres.gerer',
    'PUT /api/v1/admin/tribus/{tribu_id}/patriarche': 'tribus.administrer',
    'PUT /api/v1/membres/me/langue': 'membres.self',
    'PUT /api/v1/membres/me/theme': 'membres.self',
    'PUT /api/v1/membres/me/double-facteur': 'membres.self',
    'PUT /api/v1/membres/me/mfa-canal': 'membres.self',
    'GET /api/v1/membres/me/mfa': 'membres.self',
    'DELETE /api/v1/membres/me/appareils-confiance/{appareil_id}': 'membres.self',
}


def permissions_du_role(role: str) -> frozenset[str]:
    """The permissions a historical role holds (empty for an unknown role)."""
    return ROLE_PERMISSIONS.get(role, frozenset())
