"""Pure permission data: catalogue, role compat mapping, endpoint mapping.

No auth/db/fastapi import, so the security-critical mapping is unit-testable in
isolation (like app.scope). Generated from the real endpoint matrix; mirrored in
the base by migrations 0075/0076. The resolver and the FastAPI dependency live in
app.permissions_rbac.
"""
# ruff: noqa: E501
from __future__ import annotations

CATALOGUE: dict[str, dict[str, str]] = {
    'acces.administrer': {'domaine': 'acces', 'libelle': 'Accès et groupes - administrer', 'risque': 'critique', 'portee': 'global'},
    'acces.systeme': {'domaine': 'acces', 'libelle': 'Accès et groupes - administration système', 'risque': 'critique', 'portee': 'global'},
    'anniversaires.gerer': {'domaine': 'anniversaires', 'libelle': 'Anniversaires - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'attestations.gerer': {'domaine': 'attestations', 'libelle': 'Attestations - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'audit.administrer': {'domaine': 'audit', 'libelle': "Journal d'audit - administrer", 'risque': 'eleve', 'portee': 'global'},
    'bergers.consulter': {'domaine': 'bergers', 'libelle': 'Bergers - consulter', 'risque': 'faible', 'portee': 'scope'},
    # Collaboration access is a global app-entry permission: the fine boundary is
    # per-space membership (collab_espace_membre, require_espace_role), not an
    # organisational perimeter. It is declared 'global' rather than 'scope' because
    # collaboration never consumes require_perimetre, so a perimeter-scoped grant of
    # these keys would be inert (permissions_effectives only counts global grants).
    'canal.administrer': {'domaine': 'canal', 'libelle': 'Canal - administrer', 'risque': 'critique', 'portee': 'global'},
    'canal.traiter': {'domaine': 'canal', 'libelle': 'Canal - traiter les instructions', 'risque': 'eleve', 'portee': 'global'},
    'canal.voir': {'domaine': 'canal', 'libelle': 'Canal - voir les instructions', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.gerer': {'domaine': 'collaboration', 'libelle': 'Collaboration - gérer', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.modeles': {'domaine': 'collaboration', 'libelle': 'Collaboration - modèles de tableaux', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.superviser': {'domaine': 'collaboration', 'libelle': 'Collaboration - superviser', 'risque': 'faible', 'portee': 'global'},
    'collaboration.template.read': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - consulter', 'risque': 'faible', 'portee': 'global'},
    'collaboration.template.use': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - utiliser', 'risque': 'faible', 'portee': 'global'},
    'collaboration.template.create': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - créer', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.template.update': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - modifier', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.template.publish': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - publier', 'risque': 'eleve', 'portee': 'global'},
    'collaboration.template.archive': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - archiver', 'risque': 'moyen', 'portee': 'global'},
    'collaboration.template.delete': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - supprimer', 'risque': 'eleve', 'portee': 'global'},
    'collaboration.template.manage-all': {'domaine': 'collaboration', 'libelle': 'Modèles de collaboration - administrer', 'risque': 'eleve', 'portee': 'global'},
    'commissions.administrer': {'domaine': 'commissions', 'libelle': 'Commissions et missions - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'commissions.consulter': {'domaine': 'commissions', 'libelle': 'Commissions et missions - consulter', 'risque': 'faible', 'portee': 'scope'},
    'comptage.controler': {'domaine': 'comptage', 'libelle': 'Comptage - contrôler', 'risque': 'moyen', 'portee': 'scope'},
    'comptage.superviser': {'domaine': 'comptage', 'libelle': 'Comptage - superviser', 'risque': 'faible', 'portee': 'scope'},
    'comptes.administrer': {'domaine': 'comptes', 'libelle': 'Comptes - administrer', 'risque': 'critique', 'portee': 'global'},
    'comptes.systeme': {'domaine': 'comptes', 'libelle': 'Comptes - administration système', 'risque': 'critique', 'portee': 'global'},
    'consentements.administrer': {'domaine': 'consentements', 'libelle': 'Consentements - administrer', 'risque': 'eleve', 'portee': 'global'},
    'consentements.consulter': {'domaine': 'consentements', 'libelle': 'Consentements - consulter', 'risque': 'moyen', 'portee': 'global'},
    'controle.controler': {'domaine': 'controle', 'libelle': 'Contrôle - contrôler', 'risque': 'moyen', 'portee': 'scope'},
    'deblocage.superviser': {'domaine': 'deblocage', 'libelle': 'Déblocage - superviser', 'risque': 'faible', 'portee': 'scope'},
    'demandes.gerer': {'domaine': 'demandes', 'libelle': 'Demandes - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'demandes.superviser': {'domaine': 'demandes', 'libelle': 'Demandes - superviser', 'risque': 'faible', 'portee': 'scope'},
    'documents.bibliotheque': {'domaine': 'documents', 'libelle': 'Documents - bibliothèque institutionnelle', 'risque': 'moyen', 'portee': 'global'},
    'documents.gerer': {'domaine': 'documents', 'libelle': 'Documents - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'doublons.administrer': {'domaine': 'doublons', 'libelle': 'Doublons - administrer', 'risque': 'critique', 'portee': 'global'},
    'doublons.consulter': {'domaine': 'doublons', 'libelle': 'Doublons - consulter', 'risque': 'critique', 'portee': 'global'},
    'doublons.gerer': {'domaine': 'doublons', 'libelle': 'Doublons - gérer', 'risque': 'critique', 'portee': 'global'},
    'evenements.consulter': {'domaine': 'evenements', 'libelle': 'Événements - consulter', 'risque': 'faible', 'portee': 'scope'},
    'evenements.gerer': {'domaine': 'evenements', 'libelle': 'Événements - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'evenements.superviser': {'domaine': 'evenements', 'libelle': 'Événements - superviser', 'risque': 'faible', 'portee': 'scope'},
    'fonctions.consulter': {'domaine': 'fonctions', 'libelle': 'Fonctions et titres - consulter', 'risque': 'faible', 'portee': 'scope'},
    'fonctions.gerer': {'domaine': 'fonctions', 'libelle': 'Fonctions et titres - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'inscriptions.administrer': {'domaine': 'inscriptions', 'libelle': 'Inscriptions - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'inscriptions.gerer': {'domaine': 'inscriptions', 'libelle': 'Inscriptions - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'integrations.administrer': {'domaine': 'integrations', 'libelle': 'Intégrations - administrer', 'risque': 'eleve', 'portee': 'global'},
    'integrations.superviser': {'domaine': 'integrations', 'libelle': 'Intégrations - superviser', 'risque': 'moyen', 'portee': 'global'},
    'matrice-pays.consulter': {'domaine': 'matrice-pays', 'libelle': 'Matrice pays - consulter', 'risque': 'faible', 'portee': 'scope'},
    'matrice-pays.gerer': {'domaine': 'matrice-pays', 'libelle': 'Matrice pays - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'membres.administrer': {'domaine': 'membres', 'libelle': 'Membres - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'membres.consulter': {'domaine': 'membres', 'libelle': 'Membres - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'membres.gerer': {'domaine': 'membres', 'libelle': 'Membres - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'membres.self': {'domaine': 'membres', 'libelle': 'Membres - accès personnel', 'risque': 'faible', 'portee': 'self'},
    'modeles.consulter': {'domaine': 'modeles', 'libelle': 'Modèles - consulter', 'risque': 'faible', 'portee': 'scope'},
    'modeles.gerer': {'domaine': 'modeles', 'libelle': 'Modèles - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'niveaux-engagement.consulter': {'domaine': 'niveaux-engagement', 'libelle': 'Niveaux-Engagement - consulter', 'risque': 'faible', 'portee': 'scope'},
    'niveaux-engagement.gerer': {'domaine': 'niveaux-engagement', 'libelle': 'Niveaux-Engagement - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'notifications.consulter': {'domaine': 'notifications', 'libelle': 'Notifications - consulter', 'risque': 'faible', 'portee': 'scope'},
    'notifications.gerer': {'domaine': 'notifications', 'libelle': 'Notifications - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'informations.consulter': {'domaine': 'communication', 'libelle': 'Informations - consulter', 'risque': 'faible', 'portee': 'global'},
    'informations.gerer': {'domaine': 'communication', 'libelle': 'Informations - diffuser', 'risque': 'eleve', 'portee': 'global'},
    'organisation.administrer': {'domaine': 'organisation', 'libelle': 'Organisation - administrer', 'risque': 'eleve', 'portee': 'global'},
    'organisation.consulter': {'domaine': 'organisation', 'libelle': 'Organisation - consulter', 'risque': 'faible', 'portee': 'scope'},
    'organisation.supervision': {'domaine': 'tribus', 'libelle': 'Tribus - supervision', 'risque': 'eleve', 'portee': 'global'},
    'organisation.equipes': {'domaine': 'organisation', 'libelle': 'Organisation - équipes spéciales', 'risque': 'moyen', 'portee': 'global'},
    'parametres.consulter': {'domaine': 'parametres', 'libelle': 'Paramètres - consulter', 'risque': 'faible', 'portee': 'scope'},
    'parametres.gerer': {'domaine': 'parametres', 'libelle': 'Paramètres - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'participation.consulter': {'domaine': 'participation', 'libelle': 'Participation - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'participation.gerer': {'domaine': 'participation', 'libelle': 'Participation - gérer', 'risque': 'moyen', 'portee': 'scope'},
    'statistiques.consulter': {'domaine': 'statistiques', 'libelle': 'Statistiques - consulter', 'risque': 'moyen', 'portee': 'scope'},
    'tags.administrer': {'domaine': 'tags', 'libelle': 'Étiquettes - administrer', 'risque': 'eleve', 'portee': 'global'},
    'terminaux.administrer': {'domaine': 'terminaux', 'libelle': 'Terminaux - administrer', 'risque': 'eleve', 'portee': 'global'},
    'terminaux.consulter': {'domaine': 'terminaux', 'libelle': 'Terminaux - consulter', 'risque': 'faible', 'portee': 'scope'},
    'tribus.administrer': {'domaine': 'tribus', 'libelle': 'Tribus - administrer', 'risque': 'eleve', 'portee': 'scope'},
    'tribus.consulter': {'domaine': 'tribus', 'libelle': 'Tribus - consulter', 'risque': 'faible', 'portee': 'scope'},
}

# Human explanation of each atomic permission, grounded strictly in the endpoints
# it gates (ENDPOINT_PERMISSION): what it concretely allows (description) and its
# boundary, i.e. what it does NOT allow (limite). Shown in the permission matrix
# and the group editor so an administrator understands what a grant means before
# giving it. Kept separate from CATALOGUE so the security-critical catalogue shape
# (mirrored by migrations/tests) is untouched.
PERMISSION_DETAILS: dict[str, dict[str, str]] = {
    'acces.administrer': {'description': "Gérer les accès des membres: consulter le catalogue d'accès et de permissions, les groupes, les périmètres disponibles, l'accès effectif d'un membre, et ajouter ou retirer un membre d'un groupe.", 'limite': "Ne permet pas de créer, modifier ou supprimer les groupes eux-mêmes, ce qui relève de acces.systeme."},
    'acces.systeme': {'description': "Créer, modifier et supprimer les groupes d'accès qui structurent les droits de la plateforme.", 'limite': "Ne couvre pas l'affectation des membres aux groupes, qui relève de acces.administrer."},
    'anniversaires.gerer': {'description': "Déclencher manuellement l'envoi des messages d'anniversaire aux membres.", 'limite': "Ne permet pas d'éditer le modèle de message d'anniversaire, qui relève de modeles.gerer, et reste borné au périmètre attribué."},
    'attestations.gerer': {'description': "Consulter la liste des attestations et valider une attestation.", 'limite': "Aucune action au-delà de la validation n'est exposée, et l'accès reste borné au périmètre attribué."},
    'audit.administrer': {'description': "Consulter le journal d'audit retraçant les actions sensibles de la plateforme.", 'limite': "Lecture seule: aucune modification ni suppression des entrées d'audit n'est possible."},
    'bergers.consulter': {'description': "Consulter la liste des bergers.", 'limite': "Lecture seule bornée au périmètre: aucune création ni modification."},
    'canal.administrer': {'description': "Administrer le canal: configurer les émetteurs autorisés du bot d'instruction et les canaux additionnels.", 'limite': "Le tri et le traitement des instructions relèvent de canal.traiter, la simple lecture de canal.voir."},
    'canal.traiter': {'description': "Traiter les instructions du canal: prendre en charge, affecter à un espace et à des personnes, charger vers un tableau, restituer et clôturer; créer/éditer les sujets, notes et transcriptions.", 'limite': "La configuration du canal relève de canal.administrer."},
    'canal.voir': {'description': "Voir les instructions du canal (sujets, notes vocales, transcriptions, suivi) en lecture seule.", 'limite': "Ne permet ni de prendre en charge, ni d'affecter, ni d'éditer, ce qui relève de canal.traiter."},
    'collaboration.gerer': {'description': "Créer et modifier le contenu collaboratif: espaces, tableaux, colonnes, cartes, checklists, pièces jointes, commentaires, étiquettes, activités et messages du canal.", 'limite': "L'action reste bornée à l'appartenance de chaque espace collaboratif (membre de l'espace), et non à un périmètre organisationnel."},
    'collaboration.superviser': {'description': "Accéder en lecture à l'application de collaboration (espaces, tableaux, cartes, calendrier, notifications, activités, recherche) et rejoindre un espace via un jeton, marquer une carte lue ou signaler sa présence.", 'limite': "Ne permet pas de créer ni de modifier espaces, tableaux ou cartes, ce qui relève de collaboration.gerer."},
    'collaboration.template.read': {'description': "Voir le catalogue des modèles de tableaux et le détail de leur structure.", 'limite': "Ne permet ni de créer un tableau à partir d'un modèle, ni de modifier un modèle."},
    'collaboration.template.use': {'description': "Créer un tableau à partir d'un modèle publié.", 'limite': "Ne donne aucun droit sur le modèle lui-même, qui reste inchangé."},
    'collaboration.template.create': {'description': "Préparer un nouveau modèle de tableau, qui reste un brouillon jusqu'à sa publication.", 'limite': "Ne permet pas de publier : la mise à disposition relève de collaboration.template.publish."},
    'collaboration.template.update': {'description': "Modifier la structure, le nom ou la description d'un modèle.", 'limite': "Ne permet ni de publier, ni d'archiver, ni de supprimer."},
    'collaboration.template.publish': {'description': "Publier un brouillon pour le mettre à disposition des équipes, ou le renvoyer en brouillon.", 'limite': "Ne permet pas de créer ni de modifier un modèle, afin de séparer la préparation de l'approbation."},
    'collaboration.template.archive': {'description': "Retirer un modèle du catalogue sans le détruire.", 'limite': "Les tableaux déjà créés à partir de ce modèle ne sont pas affectés : leurs colonnes ont été copiées."},
    'collaboration.template.delete': {'description': "Supprimer définitivement un modèle du catalogue.", 'limite': "Irréversible. Les tableaux issus du modèle restent intacts."},
    'collaboration.template.manage-all': {'description': "Administrer tous les modèles, y compris ceux dont on n'est pas l'auteur.", 'limite': "Ne donne aucun droit sur le contenu des espaces collaboratifs."},
    'collaboration.modeles': {'description': "Accéder à la page de création de modèles de tableaux dans la collaboration et créer, modifier ou supprimer des modèles personnalisés réutilisables par les équipes.", 'limite': "Ne donne aucun droit sur le contenu des espaces; l'usage d'un modèle pour créer un tableau reste régi par collaboration.gerer et l'appartenance à l'espace."},
    'commissions.administrer': {'description': "Créer des commissions et des missions.", 'limite': "Aucun endpoint de suppression n'est exposé; la simple consultation relève de commissions.consulter et l'action reste bornée au périmètre."},
    'commissions.consulter': {'description': "Consulter la liste des commissions et des missions.", 'limite': "Lecture seule: aucune création ni modification."},
    'comptage.controler': {'description': "Enregistrer un comptage lors d'un événement.", 'limite': "Ne donne pas accès à la consultation consolidée du comptage (comptage.superviser) et reste borné au périmètre."},
    'comptage.superviser': {'description': "Consulter le comptage consolidé d'un événement.", 'limite': "Lecture seule: ne permet pas de saisir un comptage, ce qui relève de comptage.controler."},
    'comptes.administrer': {'description': "Consulter la liste des comptes utilisateurs (comptes d'accès à la plateforme).", 'limite': "Ne permet pas de créer ni de modifier un compte, ce qui relève de comptes.systeme."},
    'comptes.systeme': {'description': "Créer des comptes utilisateurs, individuellement ou en lot, et modifier un compte existant.", 'limite': "Aucun endpoint de suppression de compte n'est exposé; la consultation de la liste relève de comptes.administrer."},
    'consentements.administrer': {'description': "Créer ou mettre à jour le texte et la version d'un consentement.", 'limite': "La consultation relève de consentements.consulter et aucune suppression n'est exposée."},
    'consentements.consulter': {'description': "Consulter les consentements, le détail de chaque version et le relevé des signatures recueillies.", 'limite': "Lecture seule, mais le relevé nomme les signataires (nom, adresse, matricule) sur toute la plateforme : ne l'accordez qu'à qui doit voir l'annuaire."},
    'controle.controler': {'description': "Opérer le contrôle de présence sur le terrain: lister les événements et membres à contrôler, vérifier un code, enregistrer les arrivées et départs, et effectuer un pointage manuel.", 'limite': "Borné aux événements du périmètre de contrôle: ne donne accès ni à la gestion des membres ni aux statistiques."},
    'deblocage.superviser': {'description': "Consulter les éléments de déblocage.", 'limite': "Lecture seule bornée au périmètre: aucune action de déblocage n'est exposée."},
    'demandes.gerer': {'description': "Traiter les demandes: les prendre en charge, échanger des messages, réclamer une pièce, décider des modifications et mettre à jour leur statut.", 'limite': "La consultation de la liste et du détail des demandes relève de demandes.superviser, et le traitement reste borné au périmètre."},
    'demandes.superviser': {'description': "Consulter la liste et le détail des demandes, leurs modifications et la photo en attente.", 'limite': "Lecture seule: aucune action de traitement, qui relève de demandes.gerer."},
    'documents.bibliotheque': {'description': "Rédiger, versionner, publier et archiver les documents institutionnels : statuts, règlements, chartes, procédures.", 'limite': "Une version publiée n'est jamais modifiée : une correction ouvre la version suivante, pour que ce qui a été signé reste lisible tel quel."},
    'documents.gerer': {'description': "Accéder au contenu et à l'URL des documents rattachés aux membres.", 'limite': "Aucun endpoint de suppression de document n'est exposé, et l'accès reste borné au périmètre."},
    'doublons.administrer': {'description': "Lancer un scan de doublons et régler le seuil de détection.", 'limite': "Le tri d'une détection (confirmer, demander des documents, personnes distinctes) relève de doublons.gerer et la consultation de la liste de doublons.consulter."},
    'doublons.consulter': {'description': "Consulter la liste des doublons détectés et le seuil de détection courant.", 'limite': "Lecture seule: ne lance aucun scan et ne modifie pas le seuil."},
    'doublons.gerer': {'description': "Comparer en détail deux fiches candidates à un doublon et statuer sur une détection (confirmer le doublon, demander des documents, ou marquer comme personnes distinctes).", 'limite': "Ne lance pas de scan et ne modifie pas le seuil, ce qui relève de doublons.administrer."},
    'evenements.consulter': {'description': "Consulter les événements, leurs pièces, leur questionnaire, les réponses et les statistiques de participation.", 'limite': "Lecture seule: aucune création ni modification."},
    'evenements.gerer': {'description': "Créer, modifier, annuler, réactiver et supprimer des événements, gérer leur session, leurs tags, pièces, questionnaire et occurrences, et tester la diffusion.", 'limite': "Le déclenchement d'un sondage relève de evenements.superviser, et la gestion reste bornée au périmètre."},
    'evenements.superviser': {'description': "Déclencher un sondage rattaché à un événement.", 'limite': "Ne donne aucun accès à la création, à la modification ou à la consultation des événements eux-mêmes."},
    'fonctions.consulter': {'description': "Consulter le référentiel des fonctions et des titres.", 'limite': "Lecture seule: aucune modification."},
    'fonctions.gerer': {'description': "Créer, modifier et supprimer des fonctions et des titres du référentiel.", 'limite': "Ne couvre pas l'attribution d'une fonction à un membre, qui relève de membres.gerer."},
    'inscriptions.administrer': {'description': "Inscrire des membres à l'unité ou en lot, convertir des engagements en membres et relancer un mot de passe.", 'limite': "Le suivi courant et la décision sur une inscription relèvent de inscriptions.gerer, et l'action reste bornée au périmètre."},
    'inscriptions.gerer': {'description': "Suivre les inscriptions et engagements (tableau de bord, invitations, import, dossiers, corrections, compteurs) et statuer sur une inscription.", 'limite': "La création directe de membres et la conversion des engagements relèvent de inscriptions.administrer."},
    'integrations.administrer': {'description': "Configurer les intégrations: fournisseurs d'IA (création, activation, test, suppression), paramètres d'intégration et test d'envoi d'e-mail.", 'limite': "La simple lecture de l'état des intégrations relève de integrations.superviser."},
    'integrations.superviser': {'description': "Consulter l'état des intégrations et la santé des envois d'e-mails.", 'limite': "Lecture seule, mais la santé des envois nomme les adresses en échec, qui sont des adresses de membres : ne l'accordez qu'à qui doit les voir."},
    'matrice-pays.consulter': {'description': "Consulter la matrice des pays et leurs règles de signature.", 'limite': "Lecture seule: aucune modification."},
    'matrice-pays.gerer': {'description': "Modifier la configuration de signature d'un pays dans la matrice.", 'limite': "Ne crée ni ne supprime d'entrée pays, et reste borné au périmètre attribué."},
    'membres.administrer': {'description': "Créer, modifier et supprimer un membre, le bloquer ou le débloquer, et consulter ses connexions et sa gouvernance.", 'limite': "L'attribution des groupes d'accès relève de acces.administrer, et l'action reste bornée au périmètre."},
    'membres.consulter': {'description': "Consulter les fonctions et la photo d'un membre.", 'limite': "Lecture partielle: la liste et la fiche complète des membres relèvent de membres.gerer."},
    'membres.gerer': {'description': "Consulter la liste et la fiche des membres, gérer leurs fonctions (attribuer, modifier, retirer), demander un document et consulter l'annuaire des pays.", 'limite': "La création, la suppression et le blocage des membres relèvent de membres.administrer, et la gestion reste bornée au périmètre."},
    'membres.self': {'description': "Accès du membre à son propre espace personnel: régler sa langue, son thème, sa double authentification et son canal MFA, consulter son état MFA et révoquer un appareil de confiance.", 'limite': "Strictement limité à son propre compte: aucun accès aux données d'autres membres."},
    'modeles.consulter': {'description': "Consulter le modèle de message d'anniversaire.", 'limite': "Lecture seule: aucune modification."},
    'modeles.gerer': {'description': "Modifier le modèle de message d'anniversaire.", 'limite': "Se limite au modèle d'anniversaire et ne déclenche pas les envois, qui relèvent de anniversaires.gerer."},
    'niveaux-engagement.consulter': {'description': "Consulter la liste des niveaux d'engagement.", 'limite': "Lecture seule: aucune modification."},
    'niveaux-engagement.gerer': {'description': "Créer, modifier et supprimer les niveaux d'engagement.", 'limite': "Action bornée au périmètre attribué."},
    'notifications.consulter': {'description': "Consulter les types de notifications et le journal des échecs d'envoi.", 'limite': "Lecture seule: ne déclenche ni ne configure aucun envoi."},
    'notifications.gerer': {'description': "Configurer les types de notifications, déclencher les envois (sondages, envoi quotidien) et marquer un échec comme résolu.", 'limite': "Action bornée au périmètre attribué."},
    'informations.consulter': {'description': "Consulter les informations importantes diffusées aux membres et leurs statistiques de lecture.", 'limite': "La création et la diffusion relèvent de informations.gerer."},
    'informations.gerer': {'description': "Créer, éditer, cibler, publier, archiver les informations importantes et relancer les non-lus.", 'limite': "La suppression n'est possible que sur un brouillon: une information diffusée s'archive."},
    'organisation.administrer': {'description': "Créer, modifier, publier et supprimer les entités d'organisation: coordinations, intendances et sous-commissions.", 'limite': "La simple consultation de ces entités relève de organisation.consulter."},
    'organisation.consulter': {'description': "Consulter les coordinations, intendances et sous-commissions.", 'limite': "Lecture seule: aucune modification."},
    'organisation.supervision': {'description': "Désigner qui supervise une tribu (une personne ou une équipe spéciale), clore une supervision et consulter son historique.", 'limite': "Distinct du patriarche, qui doit appartenir à la tribu ; un superviseur peut lui être extérieur."},
    'organisation.equipes': {'description': "Gérer les équipes spéciales (équipe dirigeante, collège des bergers, groupe des assistants du fondateur) et leurs membres.", 'limite': "Distinct de la hiérarchie organisationnelle (commissions, intendances, tribus)."},
    'parametres.consulter': {'description': "Consulter les paramètres de fonctionnement (fenêtre de questionnaire, sondage de pointage).", 'limite': "Lecture seule: aucune modification."},
    'parametres.gerer': {'description': "Modifier les paramètres de fonctionnement (fenêtre de questionnaire, sondage de pointage).", 'limite': "Se limite à ces paramètres et reste borné au périmètre attribué."},
    'participation.consulter': {'description': "Consulter la participation globale consolidée.", 'limite': "Lecture seule: aucune modification."},
    'participation.gerer': {'description': "Accéder à l'analyse détaillée de la participation d'un membre.", 'limite': "Aucune action de modification des enregistrements de présence n'est exposée, et l'accès reste borné au périmètre."},
    'statistiques.consulter': {'description': "Consulter les statistiques consolidées de la plateforme.", 'limite': "Lecture seule: aucune modification."},
    'tags.administrer': {'description': "Gérer les étiquettes: créer une étiquette, consulter les étiquettes de demandes et décider de leur application à une demande.", 'limite': "Aucun endpoint de suppression d'étiquette n'est exposé."},
    'terminaux.administrer': {'description': "Enregistrer un terminal et modifier sa configuration.", 'limite': "La simple consultation relève de terminaux.consulter, et aucune suppression n'est exposée."},
    'terminaux.consulter': {'description': "Consulter la liste des terminaux.", 'limite': "Lecture seule: aucune modification."},
    'tribus.administrer': {'description': "Créer une tribu et administrer les tribus (nom, description, publication, réaffectation, suppression, désignation du patriarche).", 'limite': "La consultation des tribus relève de tribus.consulter; l'édition structurelle passe par organisation.administrer."},
    'tribus.consulter': {'description': "Consulter la liste des tribus.", 'limite': "Lecture seule: aucune modification."},
}

ROLE_PERMISSIONS: dict[str, frozenset[str]] = {
    'membre': frozenset(['membres.self']),
    'controleur': frozenset(['bergers.consulter', 'informations.consulter', 'commissions.consulter', 'comptage.controler', 'consentements.consulter', 'controle.controler', 'doublons.consulter', 'evenements.consulter', 'fonctions.consulter', 'matrice-pays.consulter', 'membres.consulter', 'membres.self', 'modeles.consulter', 'niveaux-engagement.consulter', 'notifications.consulter', 'organisation.consulter', 'parametres.consulter', 'participation.consulter', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'gestionnaire': frozenset(['collaboration.template.read', 'collaboration.template.use', 'anniversaires.gerer', 'informations.consulter', 'informations.gerer', 'attestations.gerer', 'bergers.consulter', 'canal.traiter', 'canal.voir', 'collaboration.gerer', 'collaboration.superviser', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.gerer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.consulter', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter']),
    'direction': frozenset(['collaboration.template.read', 'collaboration.template.use', 'bergers.consulter', 'informations.consulter', 'canal.voir', 'collaboration.superviser', 'commissions.consulter', 'comptage.superviser', 'consentements.consulter', 'deblocage.superviser', 'demandes.superviser', 'doublons.consulter', 'evenements.consulter', 'evenements.superviser', 'fonctions.consulter', 'integrations.superviser', 'matrice-pays.consulter', 'membres.consulter', 'membres.self', 'modeles.consulter', 'niveaux-engagement.consulter', 'notifications.consulter', 'organisation.consulter', 'parametres.consulter', 'participation.consulter', 'statistiques.consulter', 'terminaux.consulter', 'tribus.consulter', 'organisation.supervision', 'documents.bibliotheque']),
    'admin': frozenset(['collaboration.template.read', 'collaboration.template.use', 'collaboration.template.create', 'collaboration.template.update', 'collaboration.template.publish', 'collaboration.template.archive', 'collaboration.template.delete', 'collaboration.template.manage-all', 'acces.administrer', 'informations.consulter', 'informations.gerer', 'anniversaires.gerer', 'attestations.gerer', 'audit.administrer', 'bergers.consulter', 'canal.administrer', 'canal.traiter', 'canal.voir', 'collaboration.gerer', 'collaboration.modeles', 'collaboration.superviser', 'commissions.administrer', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'comptes.administrer', 'consentements.administrer', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.administrer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.administrer', 'inscriptions.gerer', 'integrations.administrer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.administrer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.administrer', 'organisation.consulter', 'organisation.supervision', 'organisation.supervision', 'organisation.equipes', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'tags.administrer', 'terminaux.administrer', 'terminaux.consulter', 'tribus.administrer', 'tribus.consulter', 'documents.bibliotheque']),
    'super_admin': frozenset(['collaboration.template.read', 'collaboration.template.use', 'collaboration.template.create', 'collaboration.template.update', 'collaboration.template.publish', 'collaboration.template.archive', 'collaboration.template.delete', 'collaboration.template.manage-all', 'acces.administrer', 'informations.consulter', 'informations.gerer', 'acces.systeme', 'anniversaires.gerer', 'attestations.gerer', 'audit.administrer', 'bergers.consulter', 'canal.administrer', 'canal.traiter', 'canal.voir', 'collaboration.gerer', 'collaboration.modeles', 'collaboration.superviser', 'commissions.administrer', 'commissions.consulter', 'comptage.controler', 'comptage.superviser', 'comptes.administrer', 'comptes.systeme', 'consentements.administrer', 'consentements.consulter', 'controle.controler', 'deblocage.superviser', 'demandes.gerer', 'demandes.superviser', 'documents.gerer', 'doublons.administrer', 'doublons.consulter', 'doublons.gerer', 'evenements.consulter', 'evenements.gerer', 'evenements.superviser', 'fonctions.consulter', 'fonctions.gerer', 'inscriptions.administrer', 'inscriptions.gerer', 'integrations.administrer', 'integrations.superviser', 'matrice-pays.consulter', 'matrice-pays.gerer', 'membres.administrer', 'membres.consulter', 'membres.gerer', 'membres.self', 'modeles.consulter', 'modeles.gerer', 'niveaux-engagement.consulter', 'niveaux-engagement.gerer', 'notifications.consulter', 'notifications.gerer', 'organisation.administrer', 'organisation.consulter', 'organisation.supervision', 'organisation.equipes', 'parametres.consulter', 'parametres.gerer', 'participation.consulter', 'participation.gerer', 'statistiques.consulter', 'tags.administrer', 'terminaux.administrer', 'terminaux.consulter', 'tribus.administrer', 'tribus.consulter', 'documents.bibliotheque']),
}

ENDPOINT_PERMISSION: dict[str, str] = {
    'GET /api/v1/admin/ai/catalogue': 'integrations.administrer',
    'GET /api/v1/admin/ai/providers': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers': 'integrations.administrer',
    'PATCH /api/v1/admin/ai/providers/{provider_id}': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers/{provider_id}/activer': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers/{provider_id}/desactiver': 'integrations.administrer',
    'DELETE /api/v1/admin/ai/providers/{provider_id}': 'integrations.administrer',
    'POST /api/v1/admin/ai/providers/{provider_id}/test': 'integrations.administrer',
    'GET /api/v1/collaboration/canal': 'canal.voir',
    'GET /api/v1/collaboration/canal/compteur': 'canal.voir',
    'GET /api/v1/collaboration/modeles-catalogue': 'collaboration.superviser',
    'GET /api/v1/collaboration/modeles-perso': 'collaboration.superviser',
    'POST /api/v1/collaboration/modeles-perso': 'collaboration.template.create',
    'PATCH /api/v1/collaboration/modeles-perso/{modele_id}': 'collaboration.template.update',
    'DELETE /api/v1/collaboration/modeles-perso/{modele_id}': 'collaboration.template.delete',
    'POST /api/v1/collaboration/canal': 'canal.traiter',
    'PATCH /api/v1/collaboration/canal/{message_id}': 'canal.traiter',
    'DELETE /api/v1/collaboration/canal/{message_id}': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/pieces': 'canal.traiter',
    'DELETE /api/v1/collaboration/canal/pieces/{piece_id}': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/notes': 'canal.traiter',
    'POST /api/v1/collaboration/canal/notes/{note_id}/transcrire': 'canal.traiter',
    'POST /api/v1/collaboration/canal/notes/{note_id}/rediger': 'canal.traiter',
    'PATCH /api/v1/collaboration/canal/notes/{note_id}': 'canal.traiter',
    'DELETE /api/v1/collaboration/canal/notes/{note_id}': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/reponses': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/creer-carte': 'canal.traiter',
    'POST /api/v1/collaboration/canal/telegram/importer': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/prise-en-charge': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/affecter': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/charger-tableau': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/restituer': 'canal.traiter',
    'POST /api/v1/collaboration/canal/{message_id}/cloturer': 'canal.traiter',
    'DELETE /api/v1/collaboration/espaces/{espace_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/restaurer': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/restaurer': 'collaboration.gerer',
    'GET /api/v1/collaboration/corbeille': 'collaboration.superviser',
    'GET /api/v1/collaboration/reglages': 'parametres.consulter',
    'PUT /api/v1/collaboration/reglages': 'parametres.gerer',
    'GET /api/v1/collaboration/espaces/{espace_id}/emetteurs': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces/{espace_id}/canal/demander-config': 'collaboration.gerer',
    'GET /api/v1/admin/collaboration/bot-demandes': 'integrations.administrer',
    'GET /api/v1/admin/collaboration/bots': 'integrations.administrer',
    'PUT /api/v1/admin/collaboration/espaces/{espace_id}/bot': 'acces.systeme',
    'DELETE /api/v1/admin/collaboration/espaces/{espace_id}/bot': 'acces.systeme',
    'POST /api/v1/collaboration/espaces/{espace_id}/emetteurs': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/emetteurs/{utilisateur_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/canal/{message_id}/workflow': 'canal.voir',
    'DELETE /api/v1/admin/fonctions/{cle}': 'fonctions.gerer',
    'DELETE /api/v1/admin/fonctions/{cle}/definitif': 'fonctions.gerer',
    'DELETE /api/v1/admin/membres/{membre_id}': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/suppression-apercu': 'membres.administrer',
    'PATCH /api/v1/admin/membres/{membre_id}/statut': 'membres.administrer',
    'GET /api/v1/admin/technical-super-admins': 'acces.systeme',
    'POST /api/v1/admin/technical-super-admins/creer': 'acces.systeme',
    'POST /api/v1/admin/technical-super-admins/{utilisateur_id}': 'acces.systeme',
    'PATCH /api/v1/admin/technical-super-admins/{utilisateur_id}/niveau': 'acces.systeme',
    'PATCH /api/v1/admin/technical-super-admins/{utilisateur_id}/activation': 'acces.systeme',
    'DELETE /api/v1/admin/technical-super-admins/{utilisateur_id}': 'acces.systeme',
    'DELETE /api/v1/admin/technical-super-admins/{utilisateur_id}/definitif': 'acces.systeme',
    'DELETE /api/v1/admin/membres/{membre_id}/fonctions/{fonction_id}': 'membres.gerer',
    'DELETE /api/v1/admin/membres/{membre_id}/groupes/{appartenance_id}': 'acces.administrer',
    'DELETE /api/v1/admin/niveaux-engagement/{cle}': 'niveaux-engagement.gerer',
    'DELETE /api/v1/admin/niveaux-engagement/{cle}/definitif': 'niveaux-engagement.gerer',
    'DELETE /api/v1/admin/organisation/{entity}/{item_id}': 'organisation.administrer',
    'GET /api/v1/admin/annuaire/pays': 'membres.gerer',
    'GET /api/v1/admin/attestations': 'attestations.gerer',
    'GET /api/v1/admin/audit': 'audit.administrer',
    'GET /api/v1/admin/bergers': 'bergers.consulter',
    'GET /api/v1/admin/catalogue-acces': 'acces.administrer',
    'GET /api/v1/admin/catalogue-permissions': 'acces.administrer',
    'GET /api/v1/reference/cibles-activite': 'membres.self',
    'GET /api/v1/admin/cibles-activite': 'evenements.consulter',
    'POST /api/v1/admin/cibles-activite': 'parametres.gerer',
    'PATCH /api/v1/admin/cibles-activite/{code}': 'parametres.gerer',
    'DELETE /api/v1/admin/cibles-activite/{code}': 'parametres.gerer',
    'GET /api/v1/admin/cibles-activite/{code}/apercu': 'evenements.consulter',
    'GET /api/v1/admin/commissions': 'commissions.consulter',
    'GET /api/v1/admin/comptage/evenements-eligibles': 'comptage.superviser',
    'GET /api/v1/admin/comptage/{evenement_id}': 'comptage.superviser',
    'GET /api/v1/admin/consentements': 'consentements.consulter',
    'GET /api/v1/admin/consentements/{cle}': 'consentements.consulter',
    'GET /api/v1/admin/coordinations': 'organisation.consulter',
    'GET /api/v1/admin/equipes-speciales': 'organisation.equipes',
    'POST /api/v1/admin/equipes-speciales': 'organisation.equipes',
    'PUT /api/v1/admin/equipes-speciales/{item_id}': 'organisation.equipes',
    'DELETE /api/v1/admin/equipes-speciales/{item_id}': 'organisation.equipes',
    'GET /api/v1/admin/equipes-speciales/{item_id}/membres': 'organisation.equipes',
    'POST /api/v1/admin/equipes-speciales/{item_id}/membres': 'organisation.equipes',
    'DELETE /api/v1/admin/equipes-speciales/{item_id}/membres/{membre_id}': 'organisation.equipes',
    'GET /api/v1/admin/organigramme/reglages': 'organisation.administrer',
    'PUT /api/v1/admin/organigramme/reglages': 'organisation.administrer',
    'GET /api/v1/admin/organigramme/versions': 'organisation.consulter',
    'POST /api/v1/admin/organigramme/versions': 'organisation.administrer',
    'GET /api/v1/admin/organigramme/versions/{version_id}': 'organisation.consulter',
    'POST /api/v1/admin/organigramme/versions/{version_id}/construire': 'organisation.administrer',
    'DELETE /api/v1/admin/organigramme/versions/{version_id}': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/versions/{version_id}/nodes': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/nodes/{node_id}/affecter': 'organisation.administrer',
    'PATCH /api/v1/admin/organigramme/nodes/{node_id}': 'organisation.administrer',
    'DELETE /api/v1/admin/organigramme/nodes/{node_id}': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/versions/{version_id}/links': 'organisation.administrer',
    'PATCH /api/v1/admin/organigramme/links/{link_id}': 'organisation.administrer',
    'DELETE /api/v1/admin/organigramme/links/{link_id}': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/versions/{version_id}/valider': 'organisation.consulter',
    'POST /api/v1/admin/organigramme/versions/{version_id}/publier': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/versions/{version_id}/restaurer': 'organisation.administrer',
    'GET /api/v1/admin/organigramme/coherence': 'organisation.consulter',
    'GET /api/v1/admin/organigramme/interims': 'organisation.consulter',
    'POST /api/v1/admin/organigramme/interims': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/interims/{interim_id}/terminer': 'organisation.administrer',
    'POST /api/v1/admin/organigramme/interims/{interim_id}/annuler': 'organisation.administrer',
    'GET /api/v1/organigramme/statistiques': 'organisation.consulter',
    'GET /api/v1/admin/deblocage/elements': 'deblocage.superviser',
    'GET /api/v1/admin/demandes': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}/modifications': 'demandes.superviser',
    'GET /api/v1/admin/demandes/{demande_id}/photo-pending': 'demandes.superviser',
    'GET /api/v1/admin/documents/{document_id}/content': 'documents.gerer',
    'GET /api/v1/admin/documents/{document_id}/url': 'documents.gerer',
    'GET /api/v1/admin/doublons': 'doublons.consulter',
    'GET /api/v1/admin/doublons/comparaison': 'doublons.gerer',
    'GET /api/v1/admin/doublons/fusion/apercu': 'doublons.gerer',
    'GET /api/v1/admin/doublons/seuil': 'doublons.consulter',
    'GET /api/v1/admin/evenements': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/participation-stats': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/questionnaire': 'evenements.consulter',
    'GET /api/v1/admin/evenements/{evenement_id}/reponses': 'evenements.consulter',
    'GET /api/v1/admin/fonctions': 'fonctions.consulter',
    'GET /api/v1/admin/fonctions/{cle}/dependances': 'fonctions.consulter',
    'POST /api/v1/admin/fonctions/{cle}/reaffecter': 'fonctions.gerer',
    'GET /api/v1/admin/groupes': 'acces.administrer',
    'GET /api/v1/admin/groupes/{groupe_id}/fiche': 'acces.administrer',
    'GET /api/v1/admin/gouvernance/reconciliation': 'acces.administrer',
    'GET /api/v1/admin/inscriptions/a-reparer': 'inscriptions.gerer',
    'GET /api/v1/admin/email/sante': 'integrations.superviser',
    'GET /api/v1/admin/email/adresse-rappel': 'integrations.administrer',
    'GET /api/v1/admin/permissions-applications': 'acces.administrer',
    'PUT /api/v1/admin/permissions-applications': 'acces.administrer',
    'GET /api/v1/admin/tribus/supervisions': 'organisation.supervision',
    'POST /api/v1/admin/tribus/supervisions': 'organisation.supervision',
    'POST /api/v1/admin/tribus/supervisions/{supervision_id}/clore': 'organisation.supervision',
    'GET /api/v1/admin/membres/{membre_id}/supervisions': 'organisation.supervision',
    'GET /api/v1/admin/equipe-dirigeante/declarations': 'organisation.equipes',
    'POST /api/v1/admin/equipe-dirigeante/declarations/{declaration_id}': 'organisation.equipes',
    'GET /api/v1/admin/bibliotheque': 'documents.bibliotheque',
    'POST /api/v1/admin/bibliotheque': 'documents.bibliotheque',
    'GET /api/v1/admin/bibliotheque/{document_id}': 'documents.bibliotheque',
    'PATCH /api/v1/admin/bibliotheque/{document_id}': 'documents.bibliotheque',
    'POST /api/v1/admin/bibliotheque/{document_id}/versions': 'documents.bibliotheque',
    'POST /api/v1/admin/bibliotheque/{document_id}/versions/{version_id}/publier': 'documents.bibliotheque',
    'GET /api/v1/membres/me/bibliotheque': 'membres.self',
    'GET /api/v1/membres/me/bibliotheque/{version_id}/fichier': 'membres.self',
    'GET /api/v1/admin/consentements/tracabilite': 'consentements.consulter',
    'GET /api/v1/admin/reglages/durees': 'parametres.consulter',
    'GET /api/v1/admin/vocabulaire': 'parametres.consulter',
    'PUT /api/v1/admin/vocabulaire/{terme}': 'parametres.gerer',
    'DELETE /api/v1/admin/vocabulaire/{terme}': 'parametres.gerer',
    'PUT /api/v1/admin/reglages/durees/{cle}': 'parametres.gerer',
    'GET /api/v1/membres/me/connexions': 'membres.self',
    'POST /api/v1/membres/me/connexions/fermer-autres': 'membres.self',
    'GET /api/v1/membres/me/telegram': 'membres.self',
    'DELETE /api/v1/membres/me/telegram': 'membres.self',
    'GET /api/v1/admin/membres/{membre_id}/envois-email': 'inscriptions.gerer',
    'POST /api/v1/admin/inscriptions/reparer-en-masse': 'inscriptions.administrer',
    'POST /api/v1/collaboration/modeles-perso/{modele_id}/publication': 'collaboration.template.publish',
    'POST /api/v1/collaboration/modeles-perso/{modele_id}/archivage': 'collaboration.template.archive',
    'GET /api/v1/admin/organisation/{entity}/{item_id}/titulaires': 'organisation.consulter',
    'GET /api/v1/admin/groupes/{groupe_id}/membres': 'acces.administrer',
    'GET /api/v1/admin/groupes/{groupe_id}/historique': 'acces.administrer',
    'GET /api/v1/admin/groupes/{groupe_id}/comparaison': 'acces.administrer',
    'POST /api/v1/admin/groupes/{groupe_id}/dupliquer': 'acces.systeme',
    'GET /api/v1/admin/inscriptions': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/dashboard': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/invitations': 'inscriptions.gerer',
    'GET /api/v1/admin/engagement/template.xlsx': 'inscriptions.gerer',
    'POST /api/v1/admin/engagement/convertir': 'inscriptions.administrer',
    'POST /api/v1/admin/engagement/import': 'inscriptions.gerer',
    'POST /api/v1/admin/engagement/invitations': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/compteurs': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/{membre_id}/corrections': 'inscriptions.gerer',
    'GET /api/v1/admin/inscriptions/{membre_id}/dossier': 'inscriptions.gerer',
    'GET /api/v1/admin/integrations': 'integrations.administrer',
    'GET /api/v1/admin/integrations/statut': 'integrations.superviser',
    'GET /api/v1/admin/intendances': 'organisation.consulter',
    'GET /api/v1/admin/membres': 'membres.gerer',
    'GET /api/v1/admin/membres/compartiments': 'membres.gerer',
    'GET /api/v1/admin/membres/{membre_id}': 'membres.gerer',
    'GET /api/v1/admin/membres/{membre_id}/acces-effectif': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/connexions': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/fonctions': 'membres.consulter',
    'GET /api/v1/admin/membres/{membre_id}/gouvernance': 'membres.administrer',
    'GET /api/v1/admin/membres/{membre_id}/groupes': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/participation-analytique': 'participation.gerer',
    'GET /api/v1/admin/membres/{membre_id}/photo-url': 'membres.consulter',
    'GET /api/v1/admin/modeles/anniversaire': 'modeles.consulter',
    'GET /api/v1/admin/niveaux-engagement': 'niveaux-engagement.consulter',
    'GET /api/v1/admin/niveaux-engagement/{cle}/dependances': 'niveaux-engagement.consulter',
    'POST /api/v1/admin/niveaux-engagement/{cle}/reaffecter': 'niveaux-engagement.gerer',
    'GET /api/v1/admin/notifications/echecs': 'notifications.consulter',
    'GET /api/v1/admin/notifications/types': 'notifications.consulter',
    'GET /api/v1/admin/informations': 'informations.consulter',
    'POST /api/v1/admin/informations': 'informations.gerer',
    'GET /api/v1/admin/informations/{info_id}': 'informations.consulter',
    'PATCH /api/v1/admin/informations/{info_id}': 'informations.gerer',
    'DELETE /api/v1/admin/informations/{info_id}': 'informations.gerer',
    'POST /api/v1/admin/informations/{info_id}/apercu-destinataires': 'informations.consulter',
    'POST /api/v1/admin/informations/{info_id}/media': 'informations.gerer',
    'POST /api/v1/admin/informations/{info_id}/publier': 'informations.gerer',
    'POST /api/v1/admin/informations/{info_id}/archiver': 'informations.gerer',
    'GET /api/v1/admin/informations/{info_id}/statistiques': 'informations.consulter',
    'GET /api/v1/admin/informations/{info_id}/export': 'informations.consulter',
    'POST /api/v1/admin/informations/{info_id}/relance': 'informations.gerer',
    'GET /api/v1/admin/communication/centre-diffusion': 'informations.consulter',
    'GET /api/v1/admin/parametres/identite-institutionnelle': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/identite-institutionnelle': 'parametres.gerer',
    'GET /api/v1/admin/dates-institutionnelles': 'parametres.consulter',
    'POST /api/v1/admin/dates-institutionnelles': 'parametres.gerer',
    'PATCH /api/v1/admin/dates-institutionnelles/{date_id}': 'parametres.gerer',
    'DELETE /api/v1/admin/dates-institutionnelles/{date_id}': 'parametres.gerer',
    'GET /api/v1/admin/dates-institutionnelles/{date_id}/versions': 'parametres.consulter',
    'POST /api/v1/admin/dates-institutionnelles/{date_id}/restaurer/{version_id}': 'parametres.gerer',
    'GET /api/v1/admin/reference-couleurs': 'parametres.consulter',
    'GET /api/v1/admin/calendrier-liturgique': 'parametres.consulter',
    'POST /api/v1/admin/calendrier-liturgique': 'parametres.gerer',
    'PATCH /api/v1/admin/calendrier-liturgique/{lit_id}': 'parametres.gerer',
    'DELETE /api/v1/admin/calendrier-liturgique/{lit_id}': 'parametres.gerer',
    'GET /api/v1/admin/calendrier-institutionnel/apercu': 'parametres.consulter',
    'GET /api/v1/admin/calendrier-institutionnel/apercu.ics': 'parametres.consulter',
    'GET /api/v1/admin/parametres/retention': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/retention': 'parametres.gerer',
    'POST /api/v1/admin/retention/executer': 'parametres.gerer',
    'GET /api/v1/admin/retention/journal': 'parametres.consulter',
    'GET /api/v1/admin/parametres/questionnaire-fenetre': 'parametres.consulter',
    'GET /api/v1/admin/parametres/questionnaire-fenetre-minutes': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/questionnaire-fenetre-minutes': 'parametres.gerer',
    'GET /api/v1/admin/parametres/hebdo-heure-envoi': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/hebdo-heure-envoi': 'parametres.gerer',
    'GET /api/v1/admin/parametres/semaine-jour-debut': 'parametres.consulter',
    'GET /api/v1/admin/parametres/sondage-pointage': 'parametres.consulter',
    'PUT /api/v1/admin/parametres/sondage-pointage': 'parametres.gerer',
    'POST /api/v1/admin/notifications/declencher-sondages': 'notifications.gerer',
    'GET /api/v1/admin/participation/global': 'participation.consulter',
    'GET /api/v1/admin/pays-signature': 'matrice-pays.consulter',
    'GET /api/v1/admin/perimetres-disponibles': 'acces.administrer',
    'GET /api/v1/admin/sous-commissions': 'organisation.consulter',
    'GET /api/v1/admin/statistiques': 'statistiques.consulter',
    'GET /api/v1/admin/tags/demandes': 'tags.administrer',
    'GET /api/v1/admin/terminaux': 'terminaux.consulter',
    'GET /api/v1/admin/applications': 'acces.administrer',
    'GET /api/v1/admin/applications/{code}/roles': 'acces.administrer',
    'GET /api/v1/admin/applications/{code}/membres': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/applications': 'acces.administrer',
    'GET /api/v1/admin/membres/{membre_id}/applications/{code}/groupes': 'acces.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/applications/{code}': 'acces.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/applications/{code}/groupes/{groupe_id}': 'acces.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/applications/{code}/roles/{role_code}': 'acces.administrer',
    'GET /api/v1/admin/tribus': 'tribus.consulter',
    'POST /api/v1/admin/tribus': 'tribus.administrer',
    'GET /api/v1/admin/types-evenements': 'evenements.consulter',
    'GET /api/v1/admin/types-evenements/couleur-suggeree': 'evenements.consulter',
    'POST /api/v1/admin/types-evenements': 'evenements.gerer',
    'PATCH /api/v1/admin/types-evenements/{type_id}': 'evenements.gerer',
    'DELETE /api/v1/admin/types-evenements/{type_id}': 'evenements.gerer',
    'GET /api/v1/admin/utilisateurs': 'comptes.administrer',
    'GET /api/v1/collaboration/calendrier': 'collaboration.superviser',
    'GET /api/v1/collaboration/cartes/{carte_id}/commentaires': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/archives': 'collaboration.superviser',
    'GET /api/v1/collaboration/admin/espaces': 'acces.administrer',
    'GET /api/v1/collaboration/espaces/{espace_id}': 'collaboration.superviser',
    'GET /api/v1/collaboration/membres': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux/{tableau_id}': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/membres': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}/membres/{membre_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/membres/{membre_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/demandes': 'collaboration.superviser',
    'POST /api/v1/collaboration/espaces/{espace_id}/demandes/{demande_id}/accepter': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/demandes/{demande_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/espaces/{espace_id}/etiquettes': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/espaces/{espace_id}/etiquettes/{etiquette_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/espaces/{espace_id}/etiquettes/{etiquette_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/espaces/{espace_id}/tableaux': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}/tableaux-archives': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux-espace': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/depuis-modele': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/tableaux-espace/{tableau_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/archive': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux-espace/{tableau_id}/participants': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux-espace/{tableau_id}/participants': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/tableaux-espace/{tableau_id}/participants/{utilisateur_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/colonnes': 'collaboration.superviser',
    'POST /api/v1/collaboration/tableaux/{tableau_id}/colonnes': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/colonnes/{colonne_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/colonnes/{colonne_id}': 'collaboration.gerer',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/cartes': 'collaboration.superviser',
    'GET /api/v1/collaboration/tableaux/{tableau_id}/cartes-archivees': 'collaboration.superviser',
    'POST /api/v1/collaboration/cartes-espace': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/cartes-espace/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/deplacer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/deplacer-tableau': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/dupliquer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/archive': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/publier': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/cartes-espace/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/commentaires': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/lu': 'collaboration.superviser',
    'POST /api/v1/collaboration/commentaires/{commentaire_id}/reaction': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/checklists': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklists/{checklist_id}/items': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklist-items/{item_id}/basculer': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/pieces': 'collaboration.gerer',
    'POST /api/v1/collaboration/commentaires/{commentaire_id}/pieces': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/pieces/{piece_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/couverture': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/commentaires/{commentaire_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/commentaires/{commentaire_id}': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/checklists/{checklist_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/checklists/{checklist_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklists/{checklist_id}/items/ordre': 'collaboration.gerer',
    'PATCH /api/v1/collaboration/checklist-items/{item_id}': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/checklist-items/{item_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/checklist-items/{item_id}/convertir': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux/{tableau_id}/colonnes/ordre': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes-espace/{carte_id}/presence': 'collaboration.superviser',
    'DELETE /api/v1/collaboration/cartes-espace/{carte_id}/presence': 'collaboration.superviser',
    'GET /api/v1/collaboration/notifications': 'collaboration.superviser',
    'POST /api/v1/collaboration/notifications/{notif_id}/lue': 'collaboration.superviser',
    'POST /api/v1/collaboration/notifications/toutes-lues': 'collaboration.superviser',
    'GET /api/v1/collaboration/moi': 'collaboration.superviser',
    'POST /api/v1/collaboration/rejoindre/{jeton}': 'collaboration.superviser',
    'GET /api/v1/collaboration/mes-cartes': 'collaboration.superviser',
    'GET /api/v1/collaboration/cartes-echeance': 'collaboration.superviser',
    'GET /api/v1/collaboration/activites': 'collaboration.superviser',
    'GET /api/v1/collaboration/cibles': 'collaboration.gerer',
    'POST /api/v1/collaboration/activites': 'collaboration.gerer',
    'GET /api/v1/collaboration/activites/{evenement_id}': 'collaboration.superviser',
    'PUT /api/v1/collaboration/activites/{evenement_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/activites/{evenement_id}/annuler': 'collaboration.gerer',
    'GET /api/v1/collaboration/activites/{evenement_id}/pieces': 'collaboration.superviser',
    'POST /api/v1/collaboration/activites/{evenement_id}/pieces': 'collaboration.gerer',
    'DELETE /api/v1/collaboration/activites/pieces/{piece_id}': 'collaboration.gerer',
    'POST /api/v1/collaboration/activites/{evenement_id}/occurrences': 'collaboration.gerer',
    'GET /api/v1/collaboration/stats': 'collaboration.superviser',
    'GET /api/v1/collaboration/espaces/{espace_id}/stats': 'collaboration.superviser',
    'GET /api/v1/collaboration/recherche': 'collaboration.superviser',
    'GET /api/v1/controle/evenements': 'controle.controler',
    'GET /api/v1/controle/membres': 'controle.controler',
    'DELETE /api/v1/admin/groupes/{groupe_id}': 'acces.systeme',
    'PATCH /api/v1/admin/demandes/{demande_id}': 'demandes.gerer',
    'PATCH /api/v1/admin/groupes/{groupe_id}': 'acces.systeme',
    'PATCH /api/v1/admin/evenements/{evenement_id}/session': 'evenements.gerer',
    'PATCH /api/v1/admin/membres/{membre_id}': 'membres.administrer',
    'PATCH /api/v1/admin/membres/{membre_id}/fonctions/{fonction_id}': 'membres.gerer',
    'PATCH /api/v1/admin/organisation/{entity}/{item_id}': 'organisation.administrer',
    'PATCH /api/v1/admin/organisation/{entity}/{item_id}/publication': 'organisation.administrer',
    'GET /api/v1/admin/organisation/{entity}/{item_id}/dependances': 'organisation.administrer',
    'POST /api/v1/admin/organisation/{entity}/{item_id}/reaffecter': 'organisation.administrer',
    'PATCH /api/v1/admin/pays-signature/{code}': 'matrice-pays.gerer',
    'PATCH /api/v1/admin/terminaux/{terminal_id}': 'terminaux.administrer',
    'PATCH /api/v1/admin/utilisateurs/{utilisateur_id}': 'comptes.systeme',
    'PATCH /api/v1/collaboration/cartes/{carte_id}': 'collaboration.gerer',
    'POST /api/v1/admin/anniversaires/declencher': 'anniversaires.gerer',
    'POST /api/v1/admin/attestations/{attestation_id}/valider': 'attestations.gerer',
    'POST /api/v1/admin/commissions': 'commissions.administrer',
    'POST /api/v1/admin/comptage': 'comptage.controler',
    'POST /api/v1/admin/consentements/{cle}': 'consentements.administrer',
    'POST /api/v1/admin/coordinations': 'organisation.administrer',
    'POST /api/v1/admin/demandes/{demande_id}/demander-piece': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/messages': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/modifications/decision': 'demandes.gerer',
    'POST /api/v1/admin/demandes/{demande_id}/prendre-en-charge': 'demandes.gerer',
    'POST /api/v1/admin/doublons/scan': 'doublons.administrer',
    'POST /api/v1/admin/doublons/fusion': 'doublons.administrer',
    'POST /api/v1/admin/doublons/{detection_id}/statut': 'doublons.gerer',
    'POST /api/v1/admin/evenements': 'evenements.gerer',
    'PUT /api/v1/admin/evenements/{evenement_id}': 'evenements.gerer',
    'PUT /api/v1/admin/evenements/{evenement_id}/tags': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/annuler': 'evenements.gerer',
    'GET /api/v1/admin/evenements/{evenement_id}/pieces': 'evenements.consulter',
    'POST /api/v1/admin/evenements/{evenement_id}/pieces': 'evenements.gerer',
    'DELETE /api/v1/admin/evenements/pieces/{piece_id}': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/occurrences': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/reactiver': 'evenements.gerer',
    'DELETE /api/v1/admin/evenements/{evenement_id}': 'evenements.gerer',
    'POST /api/v1/admin/evenements/{evenement_id}/sondage': 'evenements.superviser',
    'POST /api/v1/admin/evenements/{evenement_id}/test-diffusion': 'evenements.gerer',
    'POST /api/v1/admin/fonctions': 'fonctions.gerer',
    'POST /api/v1/admin/groupes': 'acces.systeme',
    'POST /api/v1/admin/inscriptions/membre': 'inscriptions.administrer',
    'POST /api/v1/admin/inscriptions/membres-lot': 'inscriptions.administrer',
    'POST /api/v1/admin/inscriptions/{membre_id}/decision': 'inscriptions.gerer',
    'POST /api/v1/admin/inscriptions/{membre_id}/relancer-mdp': 'inscriptions.administrer',
    'POST /api/v1/admin/integrations/test-email': 'integrations.administrer',
    'POST /api/v1/admin/intendances': 'organisation.administrer',
    'POST /api/v1/admin/membres': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/bloquer': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/debloquer': 'membres.administrer',
    'POST /api/v1/admin/membres/{membre_id}/demander-document': 'membres.gerer',
    'POST /api/v1/admin/membres/{membre_id}/fonctions': 'membres.gerer',
    'POST /api/v1/admin/membres/{membre_id}/groupes': 'acces.administrer',
    'POST /api/v1/admin/niveaux-engagement': 'niveaux-engagement.gerer',
    'POST /api/v1/admin/notifications/declencher-quotidien': 'notifications.gerer',
    'POST /api/v1/admin/notifications/echecs/{echec_id}/resolu': 'notifications.gerer',
    'POST /api/v1/admin/sous-commissions': 'organisation.administrer',
    'POST /api/v1/admin/tags': 'tags.administrer',
    'POST /api/v1/admin/tags/demandes/{demande_id}/decision': 'tags.administrer',
    'POST /api/v1/admin/terminaux': 'terminaux.administrer',
    'POST /api/v1/admin/utilisateurs': 'comptes.systeme',
    'POST /api/v1/admin/utilisateurs/lot': 'comptes.systeme',
    'POST /api/v1/collaboration/cartes': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes/{carte_id}/commentaires': 'collaboration.gerer',
    'POST /api/v1/collaboration/cartes/{carte_id}/publier': 'collaboration.gerer',
    'POST /api/v1/collaboration/tableaux': 'collaboration.gerer',
    'POST /api/v1/controle/checkin': 'controle.controler',
    'POST /api/v1/controle/checkin-manuel': 'controle.controler',
    'POST /api/v1/controle/checkout': 'controle.controler',
    'POST /api/v1/controle/verify': 'controle.controler',
    'PUT /api/v1/admin/coordinations/{item_id}': 'organisation.administrer',
    'PUT /api/v1/admin/doublons/seuil': 'doublons.administrer',
    'PUT /api/v1/admin/evenements/{evenement_id}/questionnaire': 'evenements.gerer',
    'PUT /api/v1/admin/fonctions/{cle}': 'fonctions.gerer',
    'PUT /api/v1/admin/integrations/{cle}': 'integrations.administrer',
    'PUT /api/v1/admin/intendances/{item_id}': 'organisation.administrer',
    'PUT /api/v1/admin/membres/{membre_id}/fonction': 'membres.gerer',
    'PUT /api/v1/admin/modeles/anniversaire': 'modeles.gerer',
    'PUT /api/v1/admin/niveaux-engagement/{cle}': 'niveaux-engagement.gerer',
    'PUT /api/v1/admin/notifications/types/{cle}': 'notifications.gerer',
    'PUT /api/v1/admin/parametres/questionnaire-fenetre': 'parametres.gerer',
    'PUT /api/v1/admin/parametres/semaine-jour-debut': 'parametres.gerer',
    'PUT /api/v1/admin/tribus/{tribu_id}/patriarche': 'tribus.administrer',
    'PUT /api/v1/membres/me/langue': 'membres.self',
    'PUT /api/v1/membres/me/theme': 'membres.self',
    'PUT /api/v1/membres/me/double-facteur': 'membres.self',
    'PUT /api/v1/membres/me/mfa-canal': 'membres.self',
    'GET /api/v1/membres/me/mfa': 'membres.self',
    'DELETE /api/v1/membres/me/appareils-confiance/{appareil_id}': 'membres.self',
}


def permissions_du_role(role: str) -> frozenset[str]:
    """The permissions a historical role holds (empty for an unknown role)."""
    return ROLE_PERMISSIONS.get(role, frozenset())
